### ISSUE TITLE
Every time I exit the settings, it goes back to the Video category

### ISSUE THREAD

**Issue by KynarIE** [wukko/cobalt#104]
Basically, every time I go to the settings and set it to "audio"
![image](https://user-images.githubusercontent.com/114863156/229274334-4b5e12b7-be6f-44bd-a167-34e9dcdb42b1.png)

And exit out, it automatically returns to "video"

See video below
https://user-images.githubusercontent.com/114863156/229274609-fe9c3ac1-c1c6-454a-a0d1-80bf9a0e21b8.mp4

**Comment by KynarIE** [comment]
Clicking the "auto mode" seems to have actually made it select audio

**Comment by wukko** [comment]
settings tabs aren't related to the mode switcher, i should definitely make it more obvious tho
