### ISSUE TITLE
Whole website site is down

### ISSUE THREAD

**Issue by lunaroid** [wukko/cobalt#109]
i tried chrome too, still the same result. This is what is says:
![45B921D3-496B-4B6B-8091-4578BCBAD811](https://user-images.githubusercontent.com/113505582/230693783-0ce3a873-3eb9-4de5-9b5a-c75a085fc5cb.jpeg)

**Comment by lunaroid** [comment]
That was by mistake sorry oops

**Comment by wukko** [comment]
it's back online, had a little bit of hiccup, sorry
