### ISSUE TITLE
Downloads of big YouTube videos get cut off due to Hop's gateway limits

### ISSUE THREAD

**Issue by KaneryU** [wukko/cobalt#121]
title, try : [Xnor Xnor Xnor](https://www.youtube.com/watch?v=3qnrewFcnQs )

**Comment by KaydaCant** [comment]
Having a similar issue with [this song](https://www.youtube.com/watch?v=uIQbSzkXIsk), seems to cut off around the 11 minute mark, but pretty inconsistent. (11:04, 10:56, and 11:02 were spots it cut off at)
