### ISSUE TITLE
YouTube renders sometimes get corrupted due to Hop's gateway limits

### ISSUE THREAD

**Issue by carrizo93** [wukko/cobalt#122]
![image](https://user-images.githubusercontent.com/77755182/236596140-0e4a568d-faac-44b9-9b8a-a3520a087c9b.png)

Confident that it's not an issue on my own end, as I am able to download youtube mp3s

**Comment by breakgimme** [comment]
also having this issue
on chrome canary and firefox, so not a browser issue

**Comment by wukko** [comment]
it’s an issue with instances hosted on hop, i’m continuously trying to figure out the issue behind it with the hop team

**Comment by hyperdefined** [comment]
> it’s an issue with instances hosted on hop, i’m continuously trying to figure out the issue behind it with the hop team

I recently switched [my instance](https://cobalt.fluffy.tools/) to hop, and my YouTube downloads are fine.

**Comment by wukko** [comment]
could just be the gateway limiting my container due to huge traffic or whatever

**Comment by memesoup** [comment]
Yeah this issue was happening to me everytime I tried to download something, but when I switched to 720p it worked.

**Comment by SpiritAxolotl** [comment]
vouch. I have this issue too.
