### ISSUE TITLE
FEATURE REQUEST: automatic “Best” option for video quality and codec/file extension when YouTube video detected

### ISSUE THREAD

**Issue by Swifticul** [wukko/cobalt#123]
I don’t know if this is feasable, but it would be pretty cool !!!

**Comment by wukko** [comment]
it’s already a thing!
just set quality to 4320p+ and codec to vp9:

![IMG_5030](https://user-images.githubusercontent.com/71202418/236728656-71fa4325-e040-4dfe-b902-a1fc6bd14187.jpeg)
