### ISSUE TITLE
"This stream token does not exist" error due to rollout errors on Hop

### ISSUE THREAD

**Issue by alexo310** [wukko/cobalt#125]
I've tried to download some videos and an audio and this is what appears.

**Comment by wukko** [comment]
just *try again*, hop fucked up the update rollout and deployment has been split in two for over a day. this is causing one of them to take the initial request and the other take the streaming one. stream info is kept within a single instance and cannot be shared around (for now).

i'll let you know when this issue gets solved, sorry for cause inconvenience :(  

![image](https://github.com/wukko/cobalt/assets/71202418/15bf251a-4a66-4e2b-bfa6-becf8fcf6a99)

**Comment by alexo310** [comment]
it's still happening
