### ISSUE TITLE
YouTube audio-only downloads take ages and fail on "best" format setting

### ISSUE THREAD

**Issue by Nat-the-Chicken** [wukko/cobalt#131]
I'm using cobalt in Linux Firefox (snap) on a laptop running Kubuntu 22.04. I had the audio format set to "best" because it seemed like that would be easier, faster, and result in the least data loss. But every time I tried to do an audio-only download of a normal YouTube video, it set the format to .webm, and then Firefox would display a notification with an unreasonably lengthy and slow progress bar. It always switched to "Failed due to network error" not much more than halfway through (and of course left an unplayable file behind). Switching the format to "mp3" caused an instant and seamless download.

Edit: my friend confirmed a similar thing happened for him on the same cobalt settings on Chrome Android, but it set the format to .opus, and even crashed the app rather than just failing the download. So this is probably a larger-scale bug that will affect more people than I thought.

**Comment by Nat-the-Chicken** [comment]
So it seems like there were two separate issues going on: one was a weird YouTube thing that caused re-encoding to be way faster, and the other was server-side errors that showed up when the download took too long. The latter has now been fixed (for now) by the provider change to mitosis, and it seems like the former is less of a bug and more just weird behavior that can't be changed due to the way cobalt interfaces with YouTube (or something).

I think at this point the best thing to do to avoid confusion would just be to add something to the settings text to mention that "best" may not be the _fastest_ setting, especially for YouTube. Action isn't strictly needed, it would just be really nice for casual users to know that.

**Comment by Memoirs99** [comment]
I feel like action is needed. My downloads still fail due to network error when using "best" setting for an audio-only download..

**Comment by Nat-the-Chicken** [comment]
> I feel like action is needed. My downloads still fail due to network error when using "best" setting for an audio-only download..

Even at the new URL, [https://mitosis.wuk.sh/](https://mitosis.wuk.sh/) ? Nothing has changed at co.wukko.me, you have to use the new address for the new host.
Either way, you can always just pick a format (like mp3 or ogg) as a workaround, that should make YouTube downloads work from either host.

**Comment by Memoirs99** [comment]
> Even at the new URL, https://mitosis.wuk.sh/ ? Nothing has changed at co.wukko.me, you have to use the new address for the new host. Either way, you can always just pick a format (like mp3 or ogg) as a workaround, that should make YouTube downloads work from either host.

My apologies. I wasn't aware of the newer URL. It seems to be working from there. Thanks!
