### ISSUE TITLE
Add support for Tumblr audio posts

### ISSUE THREAD

**Issue by UltimateRiff** [wukko/cobalt#135]
I tried pasting a link for two different Tumblr audio posts (linked below), and cobalt told me there was nothing to download...

- https://rf9weu8hjf789234hf9.tumblr.com/post/172006661342/everyone-thats-made-a-video-out-of-this-without
- https://pukicho.tumblr.com/post/718437379914989568/psy-fi64-pukicho-i-was-practicing-little-piano

**Comment by wukko** [comment]
i forgot that tumblr audio is a thing, my bad

will try to add support for it in next update tho

**Comment by UltimateRiff** [comment]
wow, that was fast~

thank you my good sir~

**Comment by wukko** [comment]
done in 6.0 :D
