### ISSUE TITLE
Youtube 1080p download gives Network error

### ISSUE THREAD

**Issue by Sagersl** [wukko/cobalt#136]
Settings: 

Video:1080p, Codec: H264

Audio: Format: Best, Auto

Works only with AV1 Codec.

**Comment by yeenbean** [comment]
I also have this issue. MP4 videos at 720p and below download fine, but 1080p fails. Additionally, I cannot download anything using the AV1 codec.

FWIW, this is on a self-hosted instance with no modifications to the codebase.
