### ISSUE TITLE
Instagram reels wont work

### ISSUE THREAD

**Issue by Jerry-g3** [wukko/cobalt#139]
Cant download instagram audio or video. Error:
"i don't see anything i could download by your link. try a different one!"

**Comment by wukko** [comment]
can i have the video link?

**Comment by Jerry-g3** [comment]
Thank you for the fast reply.
Every video I try , for example this one.

https://www.instagram.com/reel/CtSU37sLl12/?igshid=MzRlODBiNWFlZA==

**Comment by Jerry-g3** [comment]
Ok now it works. Tried like over 20 differnt videos and now it works.

**Comment by Jerry-g3** [comment]
Now getting the same error fo about 2days. Ints Reels wont download
