### ISSUE TITLE
api servers from new infra go down randomly 

### ISSUE THREAD

**Issue by SMWpalkia** [wukko/cobalt#140]
![image](https://github.com/wukko/cobalt/assets/136278510/87a54758-f630-49c9-bb3f-6723ab8fb2fa)
![image](https://github.com/wukko/cobalt/assets/136278510/ce8fa3d1-0d91-4c25-81aa-01b18ce6c140)
if you do see this, sorry if i don't respond immediately if at all becuase i dont plan on using this site for much

**Comment by SMWpalkia** [comment]
My internet is bad but not bad enough for it to never download a video, so that's not the issue

**Comment by wukko** [comment]
it's a skill issue from my side, i need to scale up a little more

**Comment by wukko** [comment]
also this affects all api requests, not just bilibili

should be fine now though

**Comment by SMWpalkia** [comment]
I probably should've looked at this soon but from my experience, bilibili is always the problematic one while youtube and soundcloud work just fine 

https://github.com/wukko/cobalt/assets/136278510/2cdd463d-ed47-464a-9237-3c809d31ef15

**Comment by wukko** [comment]
fixed this a few days ago
