### ISSUE TITLE
Instagram downloads don't work at random times

### ISSUE THREAD

**Issue by CoreoftheEarth** [wukko/cobalt#141]
sometimes when using reels, actually a lot of the time when using reels, i usually get a "something went wrong when i tried getting info about your link, are you sure it works?" 
(example link): https://www.instagram.com/reel/CtYV5W5sGTV/?igshid=MzRlODBiNWFlZA==
(screenshot): (https://github.com/wukko/cobalt/assets/30216323/afca80dd-e5a3-49ed-8016-bf7298e01e9c)

it is legitimately a 70/30 chance that either:
- the api goes down for a split second;
- the link wont work
- it wont work again
- does work OR;
- doesnt work for a 3rd, 4th, etc time

seriously, this only happens on instagram and instagram only links ive found. youtube, twitter, reddit, none of them have any issues like this that i have found. its genuinely an issue for me at this point and has been going on for around two months (iirc) for me at this point

i seriously love cobalt and enjoy using it but this issue sometimes causes me to fucnckjing explode and i dont wanna divorce cobalt

**Comment by wukko** [comment]
fixed in 6.2.3 :)

**Comment by CoreoftheEarth** [comment]
im so sorry
![image](https://github.com/wukko/cobalt/assets/30216323/66b67ace-62ba-44d8-a12e-2ba02af86ec0)
but its crapping out on me again

**Comment by wukko** [comment]
i need links to see why it’s happening

**Comment by CoreoftheEarth** [comment]
had this link now work a few times before cobalt got it
https://www.instagram.com/reel/CuaSvsxAqn4/?igshid=MzRlODBiNWFlZA==

**Comment by wukko** [comment]
can’t replicate :(

![](https://github.com/wukko/cobalt/assets/71202418/ae505bf4-dcad-4ce6-a670-2868ccd1fde8)

**Comment by CoreoftheEarth** [comment]
this one isnt working either :( 
https://www.instagram.com/reel/Ctpmm54Kido/?igshid=MzRlODBiNWFlZA==

idk why cobalt does this

**Comment by wukko** [comment]
okay, i need to add debug info somewhere to the web app so i can see which server **exactly** is affected. it could also be a temporary rate limit issue from instagram’s side (?).

because i _again_ can’t replicate the issue:


![](https://github.com/wukko/cobalt/assets/71202418/67977a91-b515-4c6b-a451-e5673abcb7eb)

**Comment by techwithanirudh** [comment]
I'm facing the same issue

**Comment by CoreoftheEarth** [comment]
some time in the past week or so. cobalt just decided to not work with instagram at all. ive been able to get it to work once, maybe twice, but thats it. i think im gonna stay away from it for instagram until it decides to work ;-; (we're separated)

**Comment by porterporter** [comment]
sometimes removing the tracking from the end of the link makes it work for me

https://www.instagram.com/reel/CucMhtWOPgk/?igshid=MTc4MmM1YmI2Ng== (doesn't work)

https://www.instagram.com/reel/CucMhtWOPgk/(worked)

i've been having this issue a lot lately as well

**Comment by CoreoftheEarth** [comment]
ive tried this too and it doesnt work at all when i've tried

**Comment by Rainissance** [comment]
I experienced very similar where I have to paste the link in several times to get it working. The error is very random and I don't know why it does this? https://github.com/wukko/cobalt/assets/139696929/7a723291-1379-425b-b952-cf462e90d02e

URL used: https://www.instagram.com/reel/CqiGesrA-jE/?igshid=MzRlODBiNWFlZA==

**Comment by Morg-S9** [comment]
having very similar issues here with both the website and api. 2nd screenshot is the api response from cobalt that my ios shortcut i built off it returns to me.

![image](https://github.com/wukko/cobalt/assets/56270390/d8759f40-b530-46be-b4c5-242a174e4398)
![image](https://github.com/wukko/cobalt/assets/56270390/35e6f8a3-197c-4303-ae6c-d0ea651167ac)

**Comment by xsfunc** [comment]
same

**Comment by iGerman00** [comment]
Facing the same issue too

**Comment by CoreoftheEarth** [comment]
update number three or whatever it is; i havent been able to have cobalt download _**anything**_ from Instagram _**at all**_ in the past three weeks. it just doesn't recognize that anything is downloadable. and no, nothing fixes it either. ive tried but it just doesnt wanna interact with Instagram anymore.

**Comment by CoreoftheEarth** [comment]
> Is Cobalt blacklisted from Instagram's servers? Or any changes in Instagram's API?

cobalt doesnt use the api. it just skims from the web client

**Comment by wukko** [comment]
should be fixed now, try it!

**Comment by CoreoftheEarth** [comment]
https://github.com/wukko/cobalt/assets/30216323/eded8bc4-8e1d-468d-9c44-f3740e98f5b1

i???? what the hell cobalt?? im using the pwa, on mobile.
link: https://www.instagram.com/reel/Ctx_AhuAcTq/?igshid=MzRlODBiNWFlZA==

**Comment by wukko** [comment]
one more fix was implemented yesterday, that's why everything actually works this time

**Comment by Morg-S9** [comment]
works great now, thank you!
