### ISSUE TITLE
Feedback: Capitalize Setting's Option Heading-->(quality--> Quality)

### ISSUE THREAD

**Issue by Tusharupadhyay784** [wukko/cobalt#154]
Describe the feedback
Inside the settings we can Capitalize the Option heading

To Reproduce
Steps to Reproduce the behaviour
1. Go to Home Page
2. Open Settings
3. you can see quality settings with quality heading 

Expected Output
quality's -----> Quality

**Comment by plusreed** [comment]
As per the [translation guidelines](https://github.com/wukko/cobalt#translation-guidelines), this is intentional and is the style that cobalt uses for strings:
> Text is **ALWAYS** stylized as lowercase unless it's STRESSED LIKE THIS or is an internal value like `{ContactLink}` or `{appName}`.

**Comment by wukko** [comment]
if you happened to not notice, all text in cobalt is lowercase. it’s intentional.
