### ISSUE TITLE
Reddit videos have no sound

### ISSUE THREAD

**Issue by thepwrtank18** [wukko/cobalt#164]
Example video: https://www.reddit.com/r/19th/comments/15dq77q/wha/

When you try to use cobalt (or any other downloading tool), there's no audio. Clicking "audio mode" shows this:
![image](https://github.com/wukko/cobalt/assets/57580668/52468a44-6d31-45a5-a725-e1a64b9cc505)

**Comment by polybiusproxy** [comment]
Having this issue too.

**Comment by ogohogo** [comment]
It appears to be issue with newer threads only

For example: `https://www.reddit.com/r/TikTokCringe/comments/15hce91/asian_daddy_kink/`
Response:
![image](https://github.com/wukko/cobalt/assets/78665139/2f949248-a2fb-44b4-b814-ac8ac9e9d1fa)

But older threads like `https://www.reddit.com/r/TikTokCringe/comments/wup1fg/id_be_escaping_at_the_first_chance_i_got/`
Work completely fine
![image](https://github.com/wukko/cobalt/assets/78665139/d60fcd7b-8870-411a-a158-589605fa240a)
🤔

**Comment by wukko** [comment]
reddit might have changed the audio link for newer videos, will look into it shortly 🙏

**Comment by wukko** [comment]
fixed in 7.0, go try it: https://co.wukko.me
