### ISSUE TITLE
response.status = `rate-limit` is not actually used anywhere

### ISSUE THREAD

**Issue by dumbmoron** [wukko/cobalt#171]
https://github.com/wukko/cobalt/blob/bd04de65d718fd0c6fe8a455fee28fb40efcde85/src/modules/sub/utils.js#L23-L24

https://github.com/wukko/cobalt/blob/bd04de65d718fd0c6fe8a455fee28fb40efcde85/docs/API.md?plain=1#L33

should probably drop it or start using it in next api update, since it might be somewhat misleading if it's mentioned in docs, but the response when ratelimited has .status == 'error':

https://github.com/wukko/cobalt/blob/bd04de65d718fd0c6fe8a455fee28fb40efcde85/src/core/api.js#L38-L41

**Comment by wukko** [comment]
fixed in 7.0 :)
