### ISSUE TITLE
suggestion: add explanation for instagram ratelimiting

### ISSUE THREAD

**Issue by 6ojo** [wukko/cobalt#176]
when trying to doywnload something from instagram, cobalt gets ratelimited often. i suggest a message similar to the error ones, explaining that cobalt cant get the instagram video because it is ratelimited

**Comment by wukko** [comment]
i am hoping to get this fixed soon, that’s why there’s no dedicated error message for it

**Comment by 6ojo** [comment]
oki 
![cat explodes](https://github.com/wukko/cobalt/assets/106943170/4ae251da-7f48-453b-b328-114e0305060a)
