### ISSUE TITLE
Age-restricted YouTube videos are impossible to download

### ISSUE THREAD

**Issue by wukko** [wukko/cobalt#18]

**Comment by tacohitbox** [comment]
if you have an example i could try something

**Comment by ijre** [comment]
> if you have an example i could try something

https://www.youtube.com/watch?v=VoM5j1PvnKo

**Comment by aprilkenopsia** [comment]
https://www.youtube.com/watch?v=keEtYeivlV8 im unsure if this video has a content warning, but for some reason i cant download it, maybe because is a short?

**Comment by Fyxren** [comment]
> https://www.youtube.com/watch?v=keEtYeivlV8 im unsure if this video has a content warning, but for some reason i cant download it, maybe because is a short?

This video is age-restricted for me. Besides, YouTube Shorts should be supported:
![image](https://user-images.githubusercontent.com/68126277/202400949-c8fd0fa3-4a7d-4318-9a2c-c45c6bb5fe11.png)

**Comment by wukko** [comment]
partially fixed in 4.5

**Comment by wukko** [comment]
unfortunately, this is impossible to fix due to youtube requiring all clients to sign in to "verify age". i am closing this issue as "won't fix" :(

**Comment by thepwrtank18** [comment]
log in with google functionality?

**Comment by wukko** [comment]
> log in with google functionality?

i don't want to handle user credentials, especially of something as personal as google accounts
