### ISSUE TITLE
player.vimeo.com links not supported

### ISSUE THREAD

**Issue by LemonadeSnake** [wukko/cobalt#184]
The website says it supports Vimeo, but the embed site is not supported.
![image](https://github.com/wukko/cobalt/assets/78671572/c6baff3f-3ed6-4f68-bf68-5c5f0772f0ce)

**Comment by wukko** [comment]
can you give me a sample link?

**Comment by LemonadeSnake** [comment]
sorry i forgot

**Comment by LemonadeSnake** [comment]
https://player.vimeo.com/video/142241440

**Comment by LemonadeSnake** [comment]
> https://player.vimeo.com/video/142241440

nvm just realised you fixed it, although with certain links it seems to give me an error saying it doesn't know anything about the link, assuming the privacy settings are weird or something
