### ISSUE TITLE
Opening the video file within vegas pro sometimes says "Unsupported file method"

### ISSUE THREAD

**Issue by AntiGriferFan** [wukko/cobalt#192]
![image](https://github.com/wukko/cobalt/assets/126976053/8ca28f8f-765d-429d-aba1-9d997c53390c)

**Comment by AntiGriferFan** [comment]
this happens to any youtube video i download

**Comment by AntiGriferFan** [comment]
i can download audios just fine

**Comment by wukko** [comment]
0 bytes issue has been fixed in 7.2!
