### ISSUE TITLE
trying to download a reddit GIF redirects to the shitty "image viewer"

### ISSUE THREAD

**Issue by thepwrtank18** [wukko/cobalt#198]
![image](https://github.com/wukko/cobalt/assets/57580668/cffdcd34-797f-42e3-a0aa-25fe60e68e35)

https://www.reddit.com/r/whenthe/comments/16almt9/_/

**Comment by nildotdev** [comment]
cant you just right click and save image as

**Comment by thepwrtank18** [comment]
it saves as an mp4

**Comment by ethrythedev** [comment]
> it saves as an mp4

can't reproduce, it redirects [here](https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fmxdhp6vo9fmb1.gif) for me (it can be downloaded as a gif)

**Comment by thepwrtank18** [comment]
> > it saves as an mp4
> 
> can't reproduce, it redirects [here](https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fmxdhp6vo9fmb1.gif) for me (it can be downloaded as a gif)

link redirects to image viewer for me

**Comment by ethrythedev** [comment]
works for me on firefox

https://github.com/wukko/cobalt/assets/58019814/59eb423d-4486-429d-8abd-c7ce12154041

**Comment by thepwrtank18** [comment]
Can you try it on Developer Edition, since that's what I'm using?

**Comment by ethrythedev** [comment]
i've also tested on developer edition with the same result.

note that developer edition and regular firefox both use the same user agent string, and are very similar so it's very unlikely that would make a difference.

**Comment by wukko** [comment]
could be a change on reddit's side, i also get the .gif now
