### ISSUE TITLE
Youtube MP4 encoding seems broken, at least on iOS/macOS

### ISSUE THREAD

**Issue by videah** [wukko/cobalt#20]
MP4's that I download from Youtube won't play in QuickTime and can't be saved to the Photos app. VLC can play it so it's not completely broken, but there's something up with the encoding that's causing issues.

**Comment by wukko** [comment]
youtube mp4s are in uncommon format, so less advanced players can't play them properly (#5)

**Comment by videah** [comment]
Just for some context, the reason I encountered this was because I was trying to write an iOS Shortcut that let me download videos from the share sheet to my camera roll, but the camera roll will not accept the video because it does not see it as valid. On iOS safari is the only browser engine so currently neither video option is usable on iOS.

**Comment by wukko** [comment]
[codfish made an ios shortcut already](https://twitter.com/codfish246/status/1553197073188757505)

**Comment by wukko** [comment]
cant do anything about it aside from recommending to use another device that respects your browser choice
