### ISSUE TITLE
`api/serverInfo` type of `cors` attribute is mismatched, `int` instead of `string`

### ISSUE THREAD

**Issue by GekkotaDev** [wukko/cobalt#209]
Documentation specifies `cors` is type of `string`
![image](https://github.com/wukko/cobalt/assets/114091010/fc93cc70-20f0-40ab-9d31-4079c7f4401b)

Data type of `cors` from request is `int` instead of `string`
![image](https://github.com/wukko/cobalt/assets/114091010/7ad30603-46a4-4216-9b2f-841fc72d886f)

**Comment by wukko** [comment]
fixed, thank you for noticing!
