### ISSUE TITLE
Consult Android to save videos to mobile photo albums

### ISSUE THREAD

**Issue by lpwyz** [wukko/cobalt#210]
Hello, I want to realize a function, that is, click the button to download online video to the mobile phone album. Previously, because I had a target below androidq, I directly downloaded the video to external storage, and then called the broadcast refresh. Now, leaders require that the app must target android11, so I have to face a problem. First, what path should I download online video to, The second is to call what method to refresh after downloading the video. Let the video appear in the phone album. After downloading the video, the storage space occupied by the app cannot be increased. Do you have a tool class, or do you have a recommended open source library, please. I have been working on this problem for a long time, but there is no appropriate method to solve it. Could you please.

**Comment by wukko** [comment]
im very confused, please try to be more concise and use [deepl](https://www.deepl.com/) to translate your message.
