### ISSUE TITLE
There’s no internet connection or api unavailable right now

### ISSUE THREAD

**Issue by NathanBarnes117** [wukko/cobalt#219]
Hey, when I was trying to paste of those link so it can download. I think either our internet not working or cobalt api is unavailable right now. I don’t know what’s the deal.

<img width="1080" alt="image" src="https://github.com/wukko/cobalt/assets/142867174/54c8b522-ee08-48ed-8290-f7db3d4bc0c2">

**Comment by VoxelDoesCode** [comment]
It's down for me, too. It might be the API.

**Comment by NathanBarnes117** [comment]
Ok, now it’s working! Finally! 😊

**Comment by NathanBarnes117** [comment]
> It's down for me, too. It might be the API.

Okay
