### ISSUE TITLE
Unable to download Instagram reels using Cobalt API 

### ISSUE THREAD

**Issue by meanii** [wukko/cobalt#223]
after downloading first reel from cobalt api, next reels not able to download 

message getting: 
```
i couldn't find anything about this link. check if it works and try again! some content may be region restricted, so keep that in mind.
```

is instagram blocking?

**Comment by wukko** [comment]
it seems like you're using a self-hosted api instance. you need instagram account cookies to download stuff from it efficiently!

**Comment by wukko** [comment]
important note: do NOT use your main account, make a dummy account with different email/phone number

**Comment by meanii** [comment]
yes, i have used dummy account's cookies
but still I'm not able to download it

but doing from docker-compose and enable the cookies volume

**Comment by wukko** [comment]
not sure what the issue is, but it's not related to cobalt api itself. sample cookies.json lists what cookies are needed for instagram module to work.
