### ISSUE TITLE
custom file names

### ISSUE THREAD

**Issue by skysthelimitt** [wukko/cobalt#228]
i thought it would be cool if you could have custom file names with special things you can insert for video title, creator, etc

like a user could type
{TITLE} ({CREATOR}, {VIDEOID})
and the file name could be (taking an example from a random video on my recommended)
"Win 11 is Slowing Your SSD (TechLinked, a-x2rTNukao)"

**Comment by wukko** [comment]
won't do unless cobalt ever comes in a form of a native app
