### ISSUE TITLE
change piped.video links to youtube.com

### ISSUE THREAD

**Issue by authenyoo** [wukko/cobalt#229]
its good for convenience/speed

like you click the cobalt button then the link you typed that is piped.video turns into youtube.com
could work for some invidious instances but just piped.video is easier to implement

**Comment by flexagoon** [comment]
@wukko what's the reason for this not being planned? I use Piped to watch YouTube and it's very inconvenient to have to first open the video on YouTube and only then paste the link into Cobalt.

yt-dlp has a list of YouTube frontend instances:

https://github.com/yt-dlp/yt-dlp/blob/ac817bc83efd939dca3e40c4b527d0ccfc77172b/yt_dlp/extractor/youtube.py#L316

And it just replaces all of those domains with `youtube.com`. Perhaps cobalt could do something similar? I can send a PR if you want
