### ISSUE TITLE
Crowdin for translation?

### ISSUE THREAD

**Issue by GreepTheSheep** [wukko/cobalt#23]
Just a question: can it be possible to use https://crowdin.com for translation for next time? Would be nice instead of edition json files directly

**Comment by wukko** [comment]
oh yeah this is way better, ill use it in next coming days to sort out the mess localization is atm

**Comment by msowho** [comment]
crowdin is paid, wukko can get problems with billing

**Comment by wukko** [comment]
there's a free tier that seems to be more than enough

**Comment by GreepTheSheep** [comment]
You can contact crowdin to get access for free if you run a open source projet (this)

**Comment by wukko** [comment]
[i finally did it](https://crowdin.com/project/cobalt)
