### ISSUE TITLE
Option to load cobalt with url query

### ISSUE THREAD

**Issue by liliantdn** [wukko/cobalt#234]
I'd love to have an option to add a url parameter to the website so that it's already filled in when loading the page, like so:
`https://cobalt.tools/?url=https://www.youtube.com/watch?v=jNQXAC9IVRw`.
That would make it really easy to make js bookmarklets or userscripts.
Some other nice options could be:
```
download=true/false  >  to launch the download on page load
mode=auto/audio
```

**Comment by wukko** [comment]
https://cobalt.tools/?u=https://www.youtube.com/watch?v=jNQXAC9IVRw :)

**Comment by liliantdn** [comment]
oh nice! is this documented anywhere? I did not find it after searching for a bit.

**Comment by wukko** [comment]
not really because i kind of suck at writing documentations

**Comment by wukko** [comment]
i'll try to make a document listing all features in the future though

**Comment by OutshineIssue** [comment]
@wukko I'm using this to create a bookmarket, do you think there's a chance to make it so it could start downloading immediately? This is what I'm currently using but I have to do the final click to make it work

`javascript:void(open('https://cobalt.tools/?u='+ location.href))`

**Comment by lostdusty** [comment]
no but you can use the api

**Comment by wukko** [comment]
> start downloading immediately

not possible to do due to browser security restrictions

**Comment by squeak9** [comment]
Any chance it could be even easier and just work with `cobalt.tools/https://www.youtube.com/watch?v=jNQXAC9IVRw`?  That way you could just add `cobalt.tools/` in front of any url.

**Comment by wukko** [comment]
@squeak9 new version supports links like this: `https://cobalt.tools/#https://youtu.be/dQw4w9WgXcQ`

**Comment by squeak9** [comment]
Oh, that's a lot simpler to remember! Good to know, thanks! 👍 
It would be perfect if it worked with nothing but `cobalt.tools/` , that's how other websites like farside.link and archive.today does it.
But if it's a lot more work then I understand 😃
