### ISSUE TITLE
Issue with soundcloud only downloading first 30 seconds of audio

### ISSUE THREAD

**Issue by Pep-Tea** [wukko/cobalt#24]
After downloading 5 songs from soundcloud with no problems it started to only download the first 30 seconds. I have tried multiple different songs in both smart and audio only mode as well as different audio formats and nothing seems to work.

**Comment by wukko** [comment]
can you please send me links to songs that ended up being 30 seconds only?

**Comment by c0hen** [comment]
Using yt-dlp to download songs that are restricted (Not available in X_country) on Soundcloud resulted in only first 30 seconds of audio per song when downloading from the restricted country. I guess Soundcloud leaves a teaser.

https://soundcloud.com/aesop-rock-official/albums
https://soundcloud.com/altblkera/albums
