### ISSUE TITLE
whenever i go to the co.wuk.sh website i get this.

### ISSUE THREAD

**Issue by Biggrafis** [wukko/cobalt#244]
![PLEAAAAAAAASE HELP DUDES](https://github.com/wukko/cobalt/assets/148593422/58b2823d-f534-446e-a346-bd260ea7c434)

Is this supposed to happen? sorry if i sound stupid.

**Comment by wukko** [comment]
if you mean the error message, then yes. if you're talking about overwatch gameplay, then it's your browser's picture in picture window.

**Comment by Biggrafis** [comment]
how do i make the error message not appear?

**Comment by Biggrafis** [comment]
i just realized that im supposed to go on the cobalt.tools website. oops
