### ISSUE TITLE
Convert GIFs from Twitter to actual GIF format

### ISSUE THREAD

**Issue by Emasoft** [wukko/cobalt#250]
Please add support for downloading GIFs from X (ex Twitter)-
For example:

https://twitter.com/mitarashi_santa/status/1726916289074241777
https://x.com/mitarashi_santa/status/1726916289074241777
https://x.com/mitarashi_santa/status/1723297185176138028
https://x.com/mitarashi_santa/status/1725110555722285471
https://x.com/mitarashi_santa/status/1720756662045475007

**Comment by wukko** [comment]
gifs on twitter are actually looping mp4 videos, so i suppose you want me to make cobalt convert them to .gif?

**Comment by timescam** [comment]
> gifs on twitter are actually looping mp4 videos, so i suppose you want me to make cobalt convert them to .gif?

that would be nice qol update
