### ISSUE TITLE
Suggestion: Allow video length limit to be customizable

### ISSUE THREAD

**Issue by tacohitbox** [wukko/cobalt#26]
![Error saying you cannot download videos over 32 minutes long.](https://user-images.githubusercontent.com/87399016/187711901-a6b28992-4e02-47a3-948f-65808cd9b6f4.png)

I'm selfhosting an instance of cobalt and I was wondering if it was possible to make that customizable rather than being locked to 32 minutes.

EDIT: Fix grammar mistake.

**Comment by wukko** [comment]
you can change length limits in config.json!

however, i do see how it'd make sense to move these values to .env file, ill look into that

**Comment by tacohitbox** [comment]
oh! i thought it was only one config because of the setup thing, thanks for telling me though!

idk if i should make a new issue for this but if enough people make instances of cobalt do you think you'd make an instance list? i love this project and want to help decentralize it if possible :)
