### ISSUE TITLE
file length

### ISSUE THREAD

**Issue by mrjk990** [wukko/cobalt#265]
can you please add file length to api ?

```
{
"status":"stream",
"url":https://us2-co.wuk.sh/api/stream?t=................", 
"length: 2394978, 
}
```

**Comment by dumbmoron** [comment]
where the file length is known, it will be provided using the `content-length` header when you request the stream URL provided in `url`. otherwise if that header is absent, the content length is not known as the file is generated on the fly

**Comment by wukko** [comment]
i could only make the api give you approximate file size, but that's far from ideal
