### ISSUE TITLE
Support Cloud Storage

### ISSUE THREAD

**Issue by sh3raawii** [wukko/cobalt#266]
I would like to run an instance of Cobalt that downloads to a configurable cloud storage provider such as Amazon S3

**Comment by dumbmoron** [comment]
This is most probably out of scope for cobalt, if you need this i would advise you to self host, and write a separate script/service that accesses cobalt API and does whatever you want with the stream outputs

**Comment by wukko** [comment]
this is indeed out of scope, at least for any foreseeable future. you're welcome to make a PR with that feature though!
