### ISSUE TITLE
video/audio will download, but not?

### ISSUE THREAD

**Issue by veepss** [wukko/cobalt#267]
this happens occasionally and each time it's increasingly annoying.

as shown in the screenshots, the video will be shown to download but won't take any storage. the file exists in its designated folder, but the actual substance of the file will not. I'm wondering if there's some kind of fix or if anyone else has encountered this issue. thank you regardless.
![SSX_c](https://github.com/wukko/cobalt/assets/153411080/89c714ce-74fa-41c4-8a52-d3980bd9e634)
![SSX_c (2)](https://github.com/wukko/cobalt/assets/153411080/a4c691e0-dfb7-4454-98c8-26cd79ac1e2c)

**Comment by wukko** [comment]
hey, the issue was temporary and has now been fixed. just delete broken files and download them again!
