### ISSUE TITLE
Soundcloud downloads sound like a filter was applied

### ISSUE THREAD

**Issue by Taureon** [wukko/cobalt#269]
How 2 reproduce:
1. Find song on soundcloud
2. Download it using the soundcloud link
3. Listen to it (Headphones recommended)

Effects:
* Song sounds like it was passed through a small filter

**Comment by wukko** [comment]
not really sure what you mean as both web app and cobalt use *the same exact audio file*

cobalt can't download paid content, if you're talking about higher quality audio with go+ subscription

**Comment by wukko** [comment]
i'm closing this issue as there was no explanation for three weeks and i couldn't reproduce what you described
