### ISSUE TITLE
Instagram Logout

### ISSUE THREAD

**Issue by MHaris-180** [wukko/cobalt#270]
its working fine but when some more request it keep my instagram account logout after every 5 to 10 request then i have to again login replace cookies then it work?how to solve this issue beacuse live cobalt api working fine on so many request. any suggestions???

**Comment by dumbmoron** [comment]
the cobalt api doesnt do anything special, it runs the exact same code thats in this repo (as you would expect).

**Comment by MHaris-180** [comment]
but im also using the same code but in start it was working fine.but now the instagram account assossiated with that cookies is logout due to suspicious behvior.
Any help any suggestion means alot.

**Comment by wukko** [comment]
this issue is not related to cobalt *specifically*, therefore we can't really help you

**Comment by wukko** [comment]
it seems like there's something wrong with your instagram account though
