### ISSUE TITLE
Can't download from Soundcloud if no opus audio is available

### ISSUE THREAD

**Issue by abUwUser** [wukko/cobalt#273]
Cobalt only thinks a Soundcloud music is valid if it includes a dash in its URL. For example: Downloading the music [Credits](https://soundcloud.com/frums/credits), which has the url `https://soundcloud.com/frums/credits`, that does not include a dash, will not download. But downloading its [extended version](https://soundcloud.com/frums/credits-ex), which includes a dash in its URL (`https://soundcloud.com/frums/credits-ex`), will download

**Comment by hllhnd** [comment]
From my testing, it seems it has nothing to do with hyphens in the song name. I tried [a different song without a hyphen from the same artist](https://soundcloud.com/frums/hall) and it downloads fine.

Instead, it seems that Soundcloud is outright not providing an Opus transcoding *for this specific song*, which Cobalt [does not account for](https://github.com/wukko/cobalt/blob/0014c8b9fb63d02f0510acc7c6e26cbc4efb97d6/src/modules/processing/services/soundcloud.js#L62).

It seems the obvious fix is using the mp3 encoding as a fallback, but I don't know if this would pose an issue. Would this fix cause any issues @wukko?

**Comment by wukko** [comment]
this fix wouldn't cause any issues, i assumed soundcloud provides opus for all songs, but apparently not lol
