### ISSUE TITLE
Youtube videos unable to be added to video editor unless re encoded or downloaded in 720p

### ISSUE THREAD

**Issue by Javadog64** [wukko/cobalt#277]
Downloading a video from YouTube in 1080p and placing it into Movie Studio Platinum 14.0 shows a "None of the files dropped on Movie Studio Platinum could be opened." error, requiring me to use Handbrake to re encode the video. The only difference that i can see in the files is that the audio bit rate increases from 4kbps to 164kbps and a video length is added.
Downloading the video in 720p or viewing the original video through VLC works fine though.

Video from Cobalt:
![image](https://github.com/wukko/cobalt/assets/97710417/793dbdbc-fa8b-4eaa-b016-ce01e8966ebe)

Video from Handbrake:
![image](https://github.com/wukko/cobalt/assets/97710417/201a0237-606c-49ef-8a39-a01cccd432b8)

**Comment by alexo310** [comment]
from what i know, this is not an issue on adobe products

**Comment by wukko** [comment]
vegas products are severely outdated and do not accept newer file containers or types.

you can work around it by recreating the container with ffmpeg:
`ffmpeg -i downloadedfilehere.mp4 -c copy outputfilehere.mp4`
