### ISSUE TITLE
YouTube videos can't be downloaded with certain resolutions.

### ISSUE THREAD

**Issue by alexo310** [wukko/cobalt#282]
I've tried to download through the site and through the api videos that are 1440p, 2160p and others (i even tried the max option in the api). However, it downloads the videos in 1080p despite being available in higher resolutions.
- This is an issue with the api, not the site by the way.

**Comment by wukko** [comment]
frontend uses same exact api, perhaps something's wrong with your request! you can open dev tools on the site and make a request for the video and see exactly what it does in network tab.

**Comment by alexo310** [comment]
i'm seeing the request in the site. it says that the video quality settings is set to 2160p but the file has the resolution of 1280x1080. i also checked the youtube video, and it goes to 1440p.

**Comment by wukko** [comment]
can you give me sample videos? those that i test are just fine 

have you tried changing the codec? h264 only goes up to 1080p and it's mentioned in settings:
<img width="568" alt="image" src="https://github.com/wukko/cobalt/assets/71202418/1e81c4f8-95c5-404a-95ab-e6fa40428405">

**Comment by alexo310** [comment]
Thank you for answering, I did not notice that 😅 however, I did try the other codecs. While the WebM worked, the av1 said that it couldn't find anything to download with that link.

**Comment by wukko** [comment]
yeah, youtube is a bit spotty with formats, not really anything i can do about it unfortunately :(

glad you figured it out though :D
