### ISSUE TITLE
Intermediate issues with YouTube downloads on main instance

### ISSUE THREAD

**Issue by JustaUser30** [wukko/cobalt#284]
It say's "i couldn't connect to the service api. maybe it's down, or cobalt got blocked"

**Comment by PC-web-Windows** [comment]
same :(

**Comment by wukko** [comment]
hey! we're aware of the issue and are working on a fix, you can track the status on https://status.cobalt.tools or https://twitter.com/justusecobalt or on our discord server.

i will also reply to this issue when it's all fixed up, so you'll get an email notification (if you have them enabled in your github account settings).

**Comment by wukko** [comment]
thank you for creating the issue btw, i forgot to do it myself 🥲

**Comment by JustaUser30** [comment]
Thank you and merry Christmas

**Comment by wukko** [comment]
fixed! should be fine now

merry christmas yall :D
