### ISSUE TITLE
Audios downloaded displaying unusually long lengths in Music (MacOS)

### ISSUE THREAD

**Issue by xxDementia** [wukko/cobalt#29]
Whenever I download just the audio from a YouTube/Soundcloud link, Music app displays song as being 6+ hours long
![image](https://user-images.githubusercontent.com/69117597/188295588-29af8b9d-4f75-4817-b631-94bc87520306.png)
![image](https://user-images.githubusercontent.com/69117597/188295601-6b2df97c-71a7-40a3-8fa7-4ad06db26ac9.png)

Consistently 6:12:49, displays as normal length in audio data

**Comment by wukko** [comment]
what's the format you used? best?

**Comment by xxDementia** [comment]
used wav and mp3, music doesn't accept ogg files apparently

**Comment by wukko** [comment]
try best format for soundcloud and lmk if audio length is fine or not

seems like something's up with conversion or music app

**Comment by xxDementia** [comment]
tried downloading from soundcloud using best format, seems like another issue popped up because i tried downloading 4 separate songs nothing's working
![image](https://user-images.githubusercontent.com/69117597/188296058-edf4a705-9245-4403-8064-00ae0197a98e.png)

**Comment by wukko** [comment]
can i have links to those songs?

also, what browser are you using?

**Comment by xxDementia** [comment]
https://soundcloud.com/zacattackk_official/end11-vampires-of-the-fjords
https://soundcloud.com/zacattackk_official/map-intro-survivors-hideout
https://soundcloud.com/diamondcup67/company-man
https://soundcloud.com/diamondcup67/im-too-crazy

using safari right now, perhaps i could test on a different browser

**Comment by wukko** [comment]
yeah try another browser cause i never tested cobalt in safari and can't promise that it's not an issue related to the browser

**Comment by xxDementia** [comment]
same issue, suspecting it might be something on my end possibly??
![image](https://user-images.githubusercontent.com/69117597/188296548-aba90a4f-bf2c-424c-b9fc-1bd6d0cd0732.png)

**Comment by wukko** [comment]
nope it's not just on your end, im getting the same error too

![Screenshot_20220904-095628_Firefox.png](https://user-images.githubusercontent.com/71202418/188296621-b1f351ec-5174-4226-91e6-06dc813d4526.png)

ill look into this in a bit and update you on the fix :)

**Comment by xxDementia** [comment]
alright, ty

**Comment by wukko** [comment]
just updated [co.wukko.me](co.wukko.me).
all 4 links you gave me now work:

![image](https://user-images.githubusercontent.com/71202418/188297651-11f21843-c923-42ea-ba63-952c88e382a3.png)

**Comment by wukko** [comment]
all files have correct lengths no matter the file extension, the length issue could be related to macos' music app

![image](https://user-images.githubusercontent.com/71202418/188297731-55654a62-ad73-4eb6-b214-a830d04d73bd.png)

**Comment by xxDementia** [comment]
sick!! also looks like that 6 hour thing is all gone too which is awesome
![image](https://user-images.githubusercontent.com/69117597/188297722-7936928a-267e-4bda-bad0-4c4812ebeafc.png)

although for youtube? still there but yeah it might just be a music thing
![image](https://user-images.githubusercontent.com/69117597/188297786-22703c8e-763e-466a-9c54-68b0397ccde4.png)

**Comment by wukko** [comment]
what's the format you used for downloading that youtube audio?

**Comment by xxDementia** [comment]
wav, opus/ogg doesn't open in music

**Comment by wukko** [comment]
it seems to be fine in foobar2000

![image](https://user-images.githubusercontent.com/71202418/188297931-05d8ffae-0fb0-4406-af50-4b5b85d9139b.png)

**Comment by xxDementia** [comment]
it's also fine in VLC as I've tested before so this could possibly be a Music thing, then again the issue for soundcloud vanished after you fixed downloading
