### ISSUE TITLE
Some Instagram Stories are not downloadable

### ISSUE THREAD

**Issue by fullpwn** [wukko/cobalt#292]
<img width="414" alt="image" src="https://github.com/wukko/cobalt/assets/57821130/948b6824-78cd-4c48-95e6-ac54cdbce642">

**Comment by wukko** [comment]
could you share a link that gave you that error?

note: cobalt can’t download stories from private accounts (for obvious reasons).

**Comment by missaustraliana** [comment]
Sure!

This is the link I tried to use.
https://www.instagram.com/stories/google/3267142423154352006
