### ISSUE TITLE
Random soundcloud link returns error

### ISSUE THREAD

**Issue by SWEDISHMEATBALLS12345674** [wukko/cobalt#293]
I have some code to pull an entire SoundCloud playlist and put it on my jellyfin server for audio streaming using my selfhosted cobalt api. today I ran into a snag where a random SoundCloud link straight up returns an error on the API.  the link in question is https://soundcloud.com/camila-elisa-vargas-castillo/04-bad-dog-no-biscuits. I've tested it with both my node API and the public one at co.wuk.sh, neither have worked.

**Comment by wukko** [comment]
fixed! docker package is currently being built and will be rolled out to co.wuk.sh within 10 minutes.

**Comment by SWEDISHMEATBALLS12345674** [comment]
Thanks! out of curiosity though, what exactly was the problem?

**Comment by wukko** [comment]
didn't accommodate for longer soundcloud usernames, i thought the max length is 24, but apparently not!

**Comment by SWEDISHMEATBALLS12345674** [comment]
ah nevermind just looked at the commit

**Comment by SWEDISHMEATBALLS12345674** [comment]
lmao

**Comment by wukko** [comment]
the update is out on co.wuk.sh :)
