### ISSUE TITLE
Sometimes TikTok doesn't return video info

### ISSUE THREAD

**Issue by catdevnull** [wukko/cobalt#294]
* https://www.tiktok.com/@petsmeowwoof/video/7316926870589672735
* https://www.tiktok.com/@monzterbearr/video/7316041720146283808

Not sure why this is happening. It also happens with https://tikmate.app, but not with https://musicaldown.com.

**Comment by wukko** [comment]
- https://www.tiktok.com/@theceezyy/video/7320729584033336609  

just adding more sample links

**Comment by paul-ssupp** [comment]
![photo_2024-01-28_22-40-55](https://github.com/wukko/cobalt/assets/39878733/c7f89e4c-686c-4fef-828c-8a6b363a3218)
@wukko As you asked, content with such clickable components like this one with 'real' (yellow colour)

**Comment by reyafyi** [comment]
+1 - happens on https://www.tiktok.com/@tsvitochik_mine/video/7277953138118692098.

**Comment by dumbmoron** [comment]
also happens for link from #360 - https://www.tiktok.com/@kevinbadminton/video/7335265467457670405
