### ISSUE TITLE
Some bilibili videos aren't downloadable

### ISSUE THREAD

**Issue by nnerdcs** [wukko/cobalt#302]
When downloading anything from Bilibili, a new tab is open briefly before an empty .mp4/.mp3 file is downloaded. This occurs both when the ?vd_source is present and missing in the link pasted.

**Comment by wukko** [comment]
could you share a sample link?

**Comment by nnerdcs** [comment]
Sorry, I meant to do this when opening the issue. These are the same video, one link includes the vd_source and the other one does not.

https://www.bilibili.com/video/BV1E14y1D7Hh/?spm_id_from=333.999.0.0&vd_source=92e476cb10e99a073f36c9dd8f835f3a

https://www.bilibili.com/video/BV1E14y1D7Hh/?spm_id_from=333.999.0.0

**Comment by AnnieCattice** [comment]
i got the same ploblem while using bilibi.

just like the following link, it will get an empty video file.

https://www.bilibili.com/video/BV18e411C7HP?spm_id_from=333.1007.tianma.2-2-5.click
