### ISSUE TITLE
"Quick Download" feature

### ISSUE THREAD

**Issue by SKCro** [wukko/cobalt#314]
**describe the feature you'd like to see**
I'd like to be able to quickly download a video using the default settings by pasting the video URL after the `cobalt.tools` URL.

For example, this...
`https://cobalt.tools/https://youtube.com/watch?v=beans`
...would instruct Cobalt to download `https://youtube.com/watch?v=beans` using either default settings or the settings the user has chosen beforehand. 

The page UI could load in with the URL already autofilled, and with the input box disabled until downloading starts (basically immediately act as if the user clicked "download").

**describe alternatives you've considered**
The "paste" feature, but it doesn't work consistently across browsers (mainly Firefox, which is my main browser) and requires another click - I'm not too sure, but I think a Quick Download feature that lets you paste directly into the URL would be both faster and work more consistently across browsers.

**additional context**
None

**Comment by wukko** [comment]
- you can enable the paste button in firefox by changing a flag following the guide that cobalt links you to.
- you can use ctrl+v to paste the video link without focusing the url area.
- you can also use this type of link https://cobalt.tools?u=linkhere
- once you enable the paste button, you can also use shift+d to paste and download a video in one keystroke.

what else is there to add?

**Comment by wukko** [comment]
no further explanation was given and feature already exists, so i'm closing this issue.
