### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by fungja005** [wukko/cobalt#328]
**bug description**
a clear and concise description of what the bug is.

**reproduction steps**
steps to reproduce the behavior:
1. go to '...'
2. click on '....'
3. download this video: **[link here]**
4. see error

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.

**links**
if applicable, add links that cause the issue. more = better.

**platform**
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
hey! the issue has been long resolved, try again!
