### ISSUE TITLE
Unable to download pictures from TikTok

### ISSUE THREAD

**Issue by ibldzn** [wukko/cobalt#330]
**bug description**
Title pretty much says it all, whenever I'm trying to download pictures from TikTok, it says `i couldn't get the full info from the shortened link.`

**reproduction steps**
steps to reproduce the behavior:
1. go to https://cobalt.tools (or the API)
2. paste the link
3. download these pictures: **https://vt.tiktok.com/ZSNoMu7Cn/**
4. see error

**screenshots**
![Screenshot_2024-01-20-23-00-20-13_984e1414ae90666a90f12ff17ec14a7f.jpg](https://github.com/wukko/cobalt/assets/51160226/86430140-415e-4429-a17b-fe2778730631)

![Screenshot_2024-01-20-23-06-25-43_6012fa4d4ddec268fc5c7112cbb265e7.jpg](https://github.com/wukko/cobalt/assets/51160226/c6044d35-2847-4f18-aef2-6fb17b7895b9)

**links**
any tiktok links that's a slideshow of pictures

**platform**
- OS: android and windows 11 (using `fetch` in javascript)
- browser: firefox nightly on android and javascript's fetch on windows
- version: firefox nightly 123.0a1 (Build #2015998247)

**additional context**
it used to work back then, not sure when did it stopped working

![Screenshot_2024-01-20-23-10-09-07_6012fa4d4ddec268fc5c7112cbb265e7.jpg](https://github.com/wukko/cobalt/assets/51160226/a28ee56f-2368-4ec4-a318-cbf5d18eb4b0)

**Comment by catdevnull** [comment]
it seems that i can't download _anything_ from tiktok now :(

**Comment by wukko** [comment]
@catdevnull can you describe the issue? provide some sample links? “thing doesn’t work” isn’t helpful at all

**Comment by catdevnull** [comment]
sorry, at the time it looked like _all_ tiktok links didn't work, so i thought that something significant changed. but it worked again. 

here's a sample link of this problem (pictures not working): https://www.tiktok.com/@dasher2xx/photo/7322175804702493984

**Comment by paul-ssupp** [comment]
@wukko 
I also have this issue
I'm using a dedicated server running this repository
This issue is actual not only for all tik-tok photo links (like this: https://vm.tiktok.com/ZM6pULPfJ)
But also for videos that have topic replies (like this: https://vm.tiktok.com/ZM6pUGGYR/)
It also may cause issues on cobalt.tools for that content

**Comment by wukko** [comment]
> But also for videos that have topic replies 
could you show me how it looks in the app? is it just a regular video?

**Comment by wukko** [comment]
photo parsing was been fixed by #336

**Comment by wukko** [comment]
@paul-ssupp as for video issues, refer to #294

**Comment by wukko** [comment]
@ibldzn @catdevnull @paul-ssupp try downloading tiktok photos now: https://cobalt.tools :)

**Comment by ibldzn** [comment]
thank you! :D
