### ISSUE TITLE
Does cobalt save media files locally on the server?

### ISSUE THREAD

**Issue by TechClusterHQ** [wukko/cobalt#334]
Hi! Thanks for this awesome project.
I am considering to host and provide my own instance to the public and have a question: Does cobalt save media files on the server (even temporarily?) or does it just stream the file directly to the end user? Does it use any extra disk space?

**Comment by wukko** [comment]
hey! it doesn’t save anything at all, therefore it doesn’t fill up disk space

**Comment by TechClusterHQ** [comment]
Thanks! If it doesn't store anything, wouldn't it be theoretically possible to host it serverlessly on CF pages or Vercel?

**Comment by wukko** [comment]
i really doubt it’d work and vercel bandwidth rates are extremely high

**Comment by TechClusterHQ** [comment]
Does using ipv6 benefit hosting this service as youtube sometimes blocks servers related to downloaders?
