### ISSUE TITLE
Unable to download music from youtube music

### ISSUE THREAD

**Issue by Kiamrei** [wukko/cobalt#335]
bug description
This youtube music url cannot download. It is unavailable

reproduction steps
steps to reproduce the behavior:

go to https://cobalt.tools/ (or the API)
paste the link
download these music:
https://youtu.be/zHTQFh6h1s4?si=4GhMF82Bggxu4b7n
https://youtu.be/mY0u_rnktdk?si=Q6SDID7MgGf6DX_2
https://youtu.be/M268Csnue9I?si=UaeKoItgTvFaIzWJ

see error
![Screenshot_2024-01-28-06-07-36-66](https://github.com/wukko/cobalt/assets/157925402/21317fc8-6ae9-4ba1-9c76-5c298fdb809a)

**Comment by wukko** [comment]
here's why this is happening: https://twitter.com/uwukko/status/1750941852088373388

**Comment by wukko** [comment]
@Kiamrei fixed, go try it: https://cobalt.tools
