### ISSUE TITLE
Language Options

### ISSUE THREAD

**Issue by UntotenTheo** [wukko/cobalt#339]
**describe the feature you'd like to see**
option to select language please :3

**describe alternatives you've considered**
uhhh none i dont think there are any

**Comment by princessmortix** [comment]
Language as page translation, or dubbed audio from youtube?

**Comment by SecularSteve** [comment]
> Language as page translation, or dubbed audio from youtube?

I think he means the former.

**Comment by princessmortix** [comment]
Dubbed audio is managed by the browser language.

**Comment by wukko** [comment]
for dub lang refer to #347

and as for page language, this is a duplicate of #93
