### ISSUE TITLE
Add support for Dailymotion

### ISSUE THREAD

**Issue by Rashedaldahmani** [wukko/cobalt#343]
I would like to have daily motion videos and khan academy be downloadable in your site because I have been using them a lot and being able to download them would be an awesome thing to have

**Comment by wukko** [comment]
could you give me some sample links for both dailymotion and khan academy

**Comment by Rashedaldahmani** [comment]
https://www.dailymotion.com/video/x8s6wuw

https://www.khanacademy.org/math/ap-calculus-ab/ab-limits-new/ab-1-2/v/introduction-to-limits-hd

**Comment by Rashedaldahmani** [comment]
Also sorry for being late

**Comment by wukko** [comment]
> https://www.khanacademy.org/math/ap-calculus-ab/ab-limits-new/ab-1-2/v/introduction-to-limits-hd

all khan academy videos are just youtube videos, click "copy link" here and paste it into cobalt! 

<img width="963" alt="image" src="https://github.com/wukko/cobalt/assets/71202418/1ff5cee6-cc6d-49f9-9390-e8f9b8a72737">

**Comment by Rashedaldahmani** [comment]
thanks bro, also how about daily motion? can you add that

**Comment by wukko** [comment]
will add support for it in future updates, that’s why i renamed the issue and left it open :)

**Comment by Rashedaldahmani** [comment]
thanks, also how does your program work?
