### ISSUE TITLE
Grammar mistakes

### ISSUE THREAD

**Issue by Taalul** [wukko/cobalt#344]
**bug description**
"sometimes youtube api sometimes..."

**reproduction steps**
steps to reproduce the behavior:
1. don't really know but it seems easy to reproduce

**screenshots**
![image](https://github.com/wukko/cobalt/assets/154693466/644d7fe8-3c71-419e-96e2-0d6fcdf02c61)

**links**
private unlisted video

**platform**
- windows
- Vivaldi
-v7.9

**additional context**
"sometimes youtube api sometimes..." decide which sometimes you want

**Comment by Taalul** [comment]
ok ill guess ill add its a youtube video, unlisted, 4k video download quality, av1.

**Comment by wukko** [comment]
oops, will fix in the morning

good catch

**Comment by Taalul** [comment]
thanks wukko, i was able to download using h264 but do you know why i can't download using av1?

**Comment by wukko** [comment]
as said in error text, youtube api doesn’t return av1 for all qualities sometimes ~~sometimes~~

**Comment by Taalul** [comment]
Спасибо и до свидания

**Comment by Taalul** [comment]
Sorry for closing I thought because you responded I should close

**Comment by wukko** [comment]
typo isn’t fixed yet, i’ll close the issue when it is 🙏
