### ISSUE TITLE
YouTube api rate limits the server (not an issue with cobalt)

### ISSUE THREAD

**Issue by nikunjmishra1998** [wukko/cobalt#346]
Dear Wukko,

I hope this message finds you well. I am writing to report an issue I have been experiencing with your  API.

For the past few days, specifically every two days, I have encountered an unexpected problem where the API returns a zero-byte output file when attempting to convert videos from YouTube. This issue has been consistently occurring, and it significantly disrupts the functionality and reliability of the service for me and potentially other users. I uploaded this API on my Git and my server. 
This works for me for two days perfectly but every two days it's suddenly returning files of 0 Bytes

**platform**
- CentOs 7 (CloudLinux)

**Comment by wukko** [comment]
not reading this until you cut the chatgpt bullshit and write text yourself 

also elaborate more and give sample links instead of scrapping the template with questions for needed information

**Comment by sidmangroliya1998** [comment]
I have tried with another audio from souncloud platform. But I am able to download it. issue only exists for youtube video
https://co.arks.cafe/

after setup on server, it works for me for two days, but after that it suddenly stops.
Is there any limits for request?

**Comment by wukko** [comment]
youtube rate limits everyone, i advise you to host your own server instead of using someone else's if you use it in huge amounts for whatever purpose 

what do you use api for?

**Comment by nikunjmishra1998** [comment]
I setup your API on my server with my domain. it works for last two days. 
in the last night it suddenly responded with 0 bytes output file from youtube videos for every format
https://search.tubidi.buzz/api/json

Above is url to view the issue 
I already hosted on my own server

I am not using web only hosted api

**Comment by wukko** [comment]
again, youtube rate limits you if requests are frequent. it usually goes away within a week. that's just how youtube api is.

you need to come up with a solution for **your server**, i can't help you with it, as it's not an issue with cobalt's codebase.

**Comment by nikunjmishra1998** [comment]
Thanks for your answer.

I just want to know if is there any request limit on cobalt rather than the rate limit.

I am already aware of the rate limit on API. but in my case API is responded as stream not rate limit in response and the file is downloading as 0 bytes.

I am already working with my server but after every 2 days these issues come up again that's why I am writing here for my final solution. 

Even the server setup is not changed and suddenly my API responded with 0 bytes output file.

As an API developer, have you faced the same issue in any cases? If yes then can you please give me basic information that how can I resolve it?

It will be really helpful for me

**Comment by wukko** [comment]
0 bytes problem is caused by rate limit **on youtube's side**, if it was on cobalt's side, then there'd be an appropriate error message.

**Comment by nikunjmishra1998** [comment]
okay, thanks for the answer I know's issue is not from the cobalt side but have any suggestions for me that can be solved on my server?

I mean how can I ignore or side rate limit on youtube's side?

**Comment by nikunjmishra1998** [comment]
hello can you please give me last answer?

**Comment by princessmortix** [comment]
Nope, you can't just bypass rate limits. Except if you have another dedicated IP.
