### ISSUE TITLE
unable to allow specific CORS origin for api

### ISSUE THREAD

**Issue by DrWarpMan** [wukko/cobalt#357]
**bug description**

I believe setting `cors=0` in the environment variables does not do anything.

[Here](https://github.com/wukko/cobalt/blob/40c17f6e33cc35be378ce5d8639d44d93e4bf57c/src/core/api.js#L18C29-L18C35) we can see that when `cors === '0'`, _corsConfig_ is set to `{ origin: process.env.webURL, optionsSuccessStatus: 200 }`.

Unfortunately, `process.env.webURL` will always be `undefined`, simply because _apiMode_ is `true` only when `process.env.webURL` is `undefined` (see [here](https://github.com/wukko/cobalt/blob/40c17f6e33cc35be378ce5d8639d44d93e4bf57c/src/cobalt.js#L24)).

**Comment by DrWarpMan** [comment]
I see that there is already an open [PR](https://github.com/wukko/cobalt/pull/353)  for a "fresh start", so you should take this issue into consideration if you intend to use the same logic to choose between running api/web mode.

**Comment by DrWarpMan** [comment]
Could you possibly take this into consideration as well?
https://developer.mozilla.org/en-US/docs/Web/Manifest#deploying_a_manifest

When using authentication in front of the cobalt frontend, I am unable to retrieve the [manifest file](https://github.com/wukko/cobalt/blob/40c17f6e33cc35be378ce5d8639d44d93e4bf57c/src/front/manifest.webmanifest) cause of the CORS issue.

I was able to make a quick workaround with Traefik, to ignore authentication just for that manifest file, but that's not desired.

Adding `crossorigin="use-credentials"` attribute [here](https://github.com/wukko/cobalt/blob/40c17f6e33cc35be378ce5d8639d44d93e4bf57c/src/modules/pageRender/page.js#L70) would fix this problem, not sure if this is the right solution.

**Comment by wukko** [comment]
hey! i've updated the env variable to be `CORS_URL` (just like in wip 8.0)

make sure you're on 7.10.3 and try again, lmk if it works this time.
_(i tested locally and it worked fine but i still would like feedback)_

**Comment by DrWarpMan** [comment]
Works.
