### ISSUE TITLE
availability API

### ISSUE THREAD

**Issue by rmbults** [wukko/cobalt#362]
**bug description**
API not available?

**reproduction steps**
you can use the main api instance ([co.wuk.sh](https://co.wuk.sh/)) in your projects.
When i click the link i get a white page with this message: {"status":"error","text":"unknown response type"}

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.

**links**
if applicable, add links that cause the issue. more = better.

**platform**
Mac OS Sanoma, MBA M2

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
api is available, please read docs on how to use it: https://github.com/wukko/cobalt/blob/current/docs/api.md
