### ISSUE TITLE
TikTok api returns void instead of video info json

### ISSUE THREAD

**Issue by wukko** [wukko/cobalt#37]

**Comment by Whanos** [comment]
Had this issue on the https://www.tiktok.com/node/share/video/@firehosegames/7145477722175769899 endpoint.
Solution is simple:
`import requests

url = "https://www.tiktok.com/node/share/video/@firehosegames/7145477722175769899"

headers = {"cookie": "tt_csrf_token=real; msToken=xdxdxd; _abck=pog~1; bm_sz=poggers",
           "User-Agent":"Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"}

r = requests.get(url, headers=headers)

print(r.text)
`

You need to add a "cookie" header, with those fields, with any text you want, it doesn't seem to matter. This works for me to fetch the data, it'll probably work for other endpoints.

**Comment by wukko** [comment]
did it in other way [here](https://github.com/wukko/cobalt/commit/e3b9fccfc3ed48a0ab6e3b0b1a3470c52d542686)
