### ISSUE TITLE
Errors when requesting tiktok content download

### ISSUE THREAD

**Issue by paul-ssupp** [wukko/cobalt#390]
**Errors when requesting tiktok content download**
When inputing any tiktok link via API or via cobalt.tools you recieve an error

**reproduction steps**
1. Pass url to POST api/json or via cobalt.tools

**screenshots**
<img width="456" alt="изображение" src="https://github.com/wukko/cobalt/assets/39878733/b1790325-e7ca-4ec4-8c7c-6b17b09c6a9e">
<img width="1136" alt="изображение" src="https://github.com/wukko/cobalt/assets/39878733/eee5af90-eeac-4f97-a96a-d6948c9d6ae6">

**links**
https://www.tiktok.com/@mr_anabo/photo/7328848106722725126
https://vm.tiktok.com/ZMMrWvfhe
https://vm.tiktok.com/ZM6pULPfJ

**platform**
Browser: Firefox, Postman
Platform: MacOS, Linux Ubuntu

**Comment by bandicuttt** [comment]
Подписываюсь, всё упало

**Comment by wukko** [comment]
привет! возможно тикток что-то поменял, но скорее всего это относится к #294.

скоро посмотрю и напишу, в чём проблема. если реально поменяли api, то выпущу обновление.
