### ISSUE TITLE
Instagram video opens new tab with player instead direct download

### ISSUE THREAD

**Issue by useronegit** [wukko/cobalt#393]
**bug description**
I just wanted to download videos from Instagram and cobalt doesn't download them directly, it opens a new tab to the video and I can play it from the browser itself and right click "download video".

**reproduction steps**
steps to reproduce the behavior:
1. go to Instagram.com
2. copy any post that is a video or a reel

**links**
a random reel from instagram
https://www.instagram.com/reel/C2_zb1ABovv/?utm_source=ig_web_copy_link

**platform**
Windows
Firefox
124

**Comment by wukko** [comment]
> i can right click to download the video

i don't see an issue here? if you don't want a new window to open, enable "ask how to save" in settings > other

**Comment by useronegit** [comment]
The problem is that it doesn't download the videos directly, but first opens a new tab, which means you have to download the video with the browser itself by right-clicking, but that's not the case with YouTube videos.

**Comment by wukko** [comment]
that's because youtube videos are rendered and instagram videos need no extra processing. when there's no extra processing needed, you get the raw video and browsers love previewing files like that.
