### ISSUE TITLE
TikTok getting "No URL Specified" when using Shortcut

### ISSUE THREAD

**Issue by Soft-Bred** [wukko/cobalt#394]
**bug description**
Using the latest version of the iOS shortcut for Cobalt, downloading TikTok videos through pasting the URL and using the share sheet gives a "No URL specified" error. I have tested this on YouTube, and the error does not occur.

**reproduction steps**
steps to reproduce the behavior:
1. Install https://www.icloud.com/shortcuts/0ff72f63304445339f8e1f59dbcafa55
2. Go to or copy `https://vm.tiktok.com/ZGePLeaLd/`
3. Share the URL to the cobalt shortcut
4. Allow cobalt to run
5. See error

**screenshots**
![F6042C0C-90AA-4D0E-A68F-F31136D376D3_1_201_a](https://github.com/wukko/cobalt/assets/60551230/52e78acd-7a13-4012-82cb-266fe0968fe9)
![AE2977A9-0042-44D2-8A55-F35F3DA6264E_1_201_a](https://github.com/wukko/cobalt/assets/60551230/5e8378ed-2a3a-47be-8c4e-e3bd9619ee11)

**links**
https://www.icloud.com/shortcuts/0ff72f63304445339f8e1f59dbcafa55
https://vm.tiktok.com/ZGePLeaLd/

**platform**
- OS iOS
- version 17.4

**additional context**
/

**Comment by wukko** [comment]
this is not an official shortcut, therefore i can't provide any support.

follow the tutorial shown by cobalt web app to save videos (i also recommend adding it to home screen for quick access)

**Comment by Soft-Bred** [comment]
Ah,understandable, shame
