### ISSUE TITLE
TikTok API is unreachable

### ISSUE THREAD

**Issue by Rizwan-Basheer** [wukko/cobalt#396]
**bug description**
tiktok downloading not works.

**links**
[if applicable, add links that cause the issue. more = better](https://www.tiktok.com/@ahsaneditz100/video/7348445366066384159)

**Comment by idrinkandiknowthing** [comment]
Me too

**Comment by idrinkandiknowthing** [comment]
Even through I run it on my own instance(localhost) I can't download tiktok video

**Comment by PassiHD2004** [comment]
happens to me as well, some videos are downloadable, but most aren't

**Comment by Write** [comment]
Is the fix applied in latest release ?

I'm using docker and still can't download TikTok videos

https://www.tiktok.com/@netflixfr/video/7354256909651823904

**Comment by lostdusty** [comment]
Yes, update your docker container

**Comment by Write** [comment]
> Yes, update your docker container

Updated and it does still throw the exact same message 🤷

**Comment by Write** [comment]
Well Okay I missed the part where it says it needs TIKTOK_DEVICE_INFO in the doc.

![Screenshot du 2024-04-12 à 14 28 27](https://github.com/wukko/cobalt/assets/541722/19b08e5d-a57e-4818-9c6b-7a1ee0879779)
