### ISSUE TITLE
Add musescore

### ISSUE THREAD

**Issue by demo308** [wukko/cobalt#398]
I want a musescore downloader

**Comment by wukko** [comment]
what's musescore? as far as i can tell it's free software: https://musescore.org/en

**Comment by Technet8394** [comment]
Musescore is a pretty boneheaded software to download from, [these guys](https://github.com/LibreScore/dl-librescore) have been trying for a while, I have the best luck with this downloading as a MIDI and importing it into librescore, which is quite jank and rarely ever works
