### ISSUE TITLE
Youtube API Unreachable

### ISSUE THREAD

**Issue by Frostee5941** [wukko/cobalt#406]
"i couldn't connect to the service api. maybe it's down, or cobalt got blocked. try again, but if error persists, check the status page or create an issue on github"

might only be happening on my end, just paste a youtube link and attempt to save it as either audio or video

using windows 10 22h2 update because windows 11 is bad

**Comment by verysillycat** [comment]
https://github.com/wukko/cobalt/assets/126973723/8c32a955-0c27-496c-b559-0a5a4d2c891b

**Comment by verysillycat** [comment]
i have the same issue on my end too

**Comment by wukko** [comment]
@Frostee5941 @verysillycat could you try now?

**Comment by BeansMP3** [comment]
still down i think

**Comment by wukko** [comment]
> still down i think
> 
> 

doesn't seem like it: https://status.cobalt.tools

**Comment by BeansMP3** [comment]
> > still down i think
> 
> doesn't seem like it: https://status.cobalt.tools

its fixed now
