### ISSUE TITLE
Cobalt sending back empty files

### ISSUE THREAD

**Issue by SWEDISHMEATBALLS12345674** [wukko/cobalt#409]
**bug description**
When i give cobalt a youtube or souncloud link, it returns a stream url which gives me a file with the correct name, but this file is empty.

**reproduction steps**
steps to reproduce the behavior:
1. git clone https://github.com/wukko/cobalt
2. run with npm
3. try and use the api
4. get empty file

I set up a new instance today as im migrating my server, the old instance worked perfectly fine and idk whats wrong.

**screenshots**
N/A, you know what your json responses look like, they all look correct but the stream link just returns nothing but a file with the right name and no content,

**platform**
- Arch Linux
- browser - its an api issue
- version - Cobalt 7.12.3

sorry to be a bother and i do wanna say that your code is great it's been super helpful for the past few months for my media server and i really like easy to use post apis to deal with stuff :3

**Comment by lostdusty** [comment]
did you run `npm run setup`?

**Comment by SWEDISHMEATBALLS12345674** [comment]
> did you run `npm run setup`?

yes ofc

**Comment by SWEDISHMEATBALLS12345674** [comment]
Hi :3

this is still an issue for me but the docker image works (im assuming the issue is arch because silly container works)
if anyone else on arch encounters this issue though i guess just switch to docker

i kinda liked having it run on node tho but eh who cares

**Comment by dumbmoron** [comment]
> Hi :3
> 
> this is still an issue for me but the docker image works (im assuming the issue is arch because silly container works) if anyone else on arch encounters this issue though i guess just switch to docker
> 
> i kinda liked having it run on node tho but eh who cares

it might be the same problem as on alpine, where the dns does not really work

you can try check if you change all the `-8` occurrences to `48` in https://github.com/wukko/cobalt/blob/current/src/modules/stream/types.js
