### ISSUE TITLE
Dailymotion videos do not contain audio

### ISSUE THREAD

**Issue by LuaGunsX** [wukko/cobalt#417]
**bug description**
Whenever I download a Dailymotion video (auto), it does not contain any audio.

**reproduction steps**
Paste in a dailymotion video, download it (make sure it's set to auto) and check the video. If there's no audio, you've reproduced it.

**links**
Original video I try to download (screamer): https://dailymotion.com/video/x1oq22
When downloaded (silent screamer): https://archive.org/details/dailymotion_x1oq22_320x240

**platform**
- Ubuntu 23.10
- Firefox
- Latest version

**Comment by wukko** [comment]
it works in vlc, what player are you using?

**Comment by wukko** [comment]
closing as neither of devs can reproduce it and there was no reply in 4 days

**Comment by LuaGunsX** [comment]
> it works in vlc, what player are you using?

opened file in firefox (pre-hardened)
