### ISSUE TITLE
New Instagram reel URL is not supported

### ISSUE THREAD

**Issue by rxnk** [wukko/cobalt#422]
**bug description**
I've discovered cobalt doesn't have support for a specific reel URL which is likely due to the regex validation.

**reproduction steps**
steps to reproduce the behavior:
input the following URL on cobalt:
`https://www.instagram.com/unreleasedsnip/reel/C2Gz6dessjX/`

**screenshots**
![image](https://github.com/wukko/cobalt/assets/95060559/29688b11-1e8f-4e83-a87f-d44e639cbe03)

**links**
[if applicable, add links that cause the issue. more = better.](https://www.instagram.com/unreleasedsnip/reel/C2Gz6dessjX/)

**platform**
- OS **Windows**
- browser **Brave**

**additional context**
These URLs are the same just different paths:
https://www.instagram.com/unreleasedsnip/reel/C2Gz6dessjX/
https://www.instagram.com/p/C2Gz6dessjX/

**Comment by wukko** [comment]
fixed in #423

it may take up to 15 minutes for the package to build and update across all processing servers. try this link on main instance after ~15 minutes.
