### ISSUE TITLE
there is no soundcloud metadata

### ISSUE THREAD

**Issue by moeinrahimi** [wukko/cobalt#424]
soundcloud does not return any metadata. by metadata I imagine data like audio name and singer, maybe I'm wrong but that's what is expect when hearing word metadata :)
![image](https://github.com/wukko/cobalt/assets/13715024/5588c594-86da-4cbe-a1a2-24da98db505e)

**Comment by wukko** [comment]
that's expected behaviour, not a bug. metadata is included in the file itself

**Comment by moeinrahimi** [comment]
oh nice! I did not know that. is this mentioned in docs?
