### ISSUE TITLE
Instagram API is unreachable

### ISSUE THREAD

**Issue by moeinrahimi** [wukko/cobalt#425]
using website or api to download instagram i get "i don't see anything i could download by your link. try a different one!"
sample url: https://www.instagram.com/stories/new_zhina/3343726075653059807/
sample url 2: https://www.instagram.com/stories/netflix/3343900474682883825/
both accounts are public

**Comment by syvnul** [comment]
Same here, today 14th April 2024 either iOS app or web interface, all Insta saves result in “No URL specified” but no issues on YT. TT etc

**Comment by lostdusty** [comment]
> Same here, today 14th April 2024 either iOS app or web interface, all Insta saves result in “No URL specified” but no issues on YT. TT etc

try again

**Comment by prabesharyal** [comment]
Yep, the issue persists. Currently, in my location, I can't download any reels or posts. So, seems like changes from the meta's end are being rolled out slowly. I use both api and website. Issue is only in instagram.
### This needs an immediate fix.

**Comment by lostdusty** [comment]
see https://status.cobalt.tools. if you need an immediate fix, consider sponsoring this project.

**Comment by wukko** [comment]
this is a global issue, not just main instance

**Comment by moeinrahimi** [comment]
why did you change issue title? it would be better to create a seperate issue for insta api being unreachable. my issue is only with stories. post and reels work just fine
