### ISSUE TITLE
feature request: bulk download playlists

### ISSUE THREAD

**Issue by DrSpaniel** [wukko/cobalt#426]
**describe the feature you'd like to see**
it would be neat to send the link of a youtube playlist and have it download each as their own mp3 in a zip.

**describe alternatives you've considered**
...

**additional context**
not much more to exlpain. it would just make the process of downloading music albums off youtube much easier.

**Comment by DrSpaniel** [comment]
![image](https://github.com/wukko/cobalt/assets/80426387/0d4bbc1b-f0b4-4959-b237-125cc6c23095)

**Comment by dumbmoron** [comment]
duplicate of #193
