### ISSUE TITLE
Redirect to cobalt's GitHub on blocked.cobalt.tools is broken

### ISSUE THREAD

**Issue by TeleKiwi** [wukko/cobalt#438]
**bug description**
When clicking on the link to this GitHub page on [blocked.cobalt.tools](url), it instead links to a non-existent "https://blocked.cobalt.tools/github.com/wukko/cobalt". This results in the user staying on the blocked page.

**reproduction steps**
steps to reproduce the behavior:
1. go to [blocked.cobalt.tools](url)
2. click on the link to "github.com/wukko/cobalt"
3. notice how you don't actually get redirected anywhere, instead staying on the blocked page.

**screenshots**
![image](https://github.com/wukko/cobalt/assets/70376250/28c64d62-990f-4b94-87c5-2947fedaf4b1)

**platform**
- OS: macOS sonoma 14.0
- browser: opera 
- version: 107

**Comment by lostdusty** [comment]
Resolved: https://x.com/uwukko/status/1780776130447839327
