### ISSUE TITLE
Twitter links return 400

### ISSUE THREAD

**Issue by hyperdefined** [wukko/cobalt#44]
![image](https://user-images.githubusercontent.com/13475823/193620706-d13d579b-ac40-49ae-a489-a95476f0e1ed.png)

Test both on my own instance (running https://github.com/wukko/cobalt/commit/af1fc24b4d81ff6c6c1f4c600a3ce82539fa6ae7) and on https://co.wukko.me.

Tested with this link: (and many other random videos) https://twitter.com/FreelanceMocha/status/1576304807794552833, returns 400.

```
https://co.wukko.me/api/json?audioFormat=best&quality=max&url=https%3A%2F%2Ftwitter.com%2FFreelanceMocha%2Fstatus%2F1576304807794552833

https://co.hyper.lol/api/json?audioFormat=best&quality=max&url=https%3A%2F%2Ftwitter.com%2FFreelanceMocha%2Fstatus%2F1576304807794552833
```

![image](https://user-images.githubusercontent.com/13475823/193621575-8972e9f1-77d6-4b92-98d2-3dbcbfcadf58.png)

**Comment by wukko** [comment]
just fixed this, someone's abusing twitter's web app bearer token and it got rate limited

i simply changed it to another one

**Comment by wukko** [comment]
i tried to download a twitter video and it didnt work and rushed to fix this

thank you anyway :D

**Comment by hyperdefined** [comment]
Thank you! Much love for making this. I will probably just get my own token for my instance <3
