### ISSUE TITLE
Hello, may I ask if you have any open-source software for developing virtual positioning for Android phones, or do you know of any open-source software? Could you please let me know

### ISSUE THREAD

**Issue by lpwyz** [wukko/cobalt#444]
Hello, may I ask if you have any open-source software for developing virtual positioning for Android phones, or do you know of any open-source software? Could you please let me know

**Comment by wukko** [comment]
what

**Comment by wukko** [comment]
are you talking about android emulator? android studio comes with one

**Comment by lostdusty** [comment]
If you're talking about cobalt in android, see https://github.com/lostdusty/gualto
