### ISSUE TITLE
i cant download youtube audio and video (in firefox 125.0.2 link is https://www.youtube.com/watch?v=AwZ65up5xvc)

### ISSUE THREAD

**Issue by bfdiamasterfan** [wukko/cobalt#446]
**bug description**
a clear and concise description of what the bug is.

**reproduction steps**
steps to reproduce the behavior:
1. go to '...'
2. click on '....'
3. download this video: **[link here]**
4. see error

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.

**links**
if applicable, add links that cause the issue. more = better.

**platform**
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
refer to #450
