### ISSUE TITLE
Can't download without a VPN

### ISSUE THREAD

**Issue by Soupman6666** [wukko/cobalt#447]
I can't download anything if i don't have a VPN activated. If i don't, it will display a error message saying it can't connect to the server currently.

- Android, Moto 5G
- Firefox
- Firefox 114.2

I live in Cuba and having to use a VPN for everything is a really common issue, because companies are forced to block cuban addresses due to the embargo. I really hope there is a way to fix this, in case it's a issue on the server's side.

**Comment by wukko** [comment]
not related to VPN, it seemed this way because you got assigned a different server by the load balancer

refer to #450 for the actual issue
