### ISSUE TITLE
Cobalt appears to be down for ALL Youtube downloads

### ISSUE THREAD

**Issue by stopmotio** [wukko/cobalt#449]
**bug description**
all servers are currently disrupted

**reproduction steps**
steps to reproduce the behavior:
1. go to cobalt.tools
2. download this video: **https://youtu.be/oDQBY989nio?si=64y_MklaXGVBrbOg**
3. see error

**screenshots**
![image](https://github.com/wukko/cobalt/assets/21047900/a8cff6f2-73c7-48c2-9437-4945838358d0)

**links**
if applicable, add links that cause the issue. more = better.

**platform**
- OS Windows 10
- browser Firefox
- version 125

**additional context**
I tried multiple different videos on both auto and audio mode.

Status report says major issues as well so it might be more than YT

**Comment by stopmotio** [comment]
I should specify the video in question isn't an indication that I'm joking it was literally just the first thing I saw on the homepage

**Comment by wukko** [comment]
refer to #450
