### ISSUE TITLE
downloading from twitter is not working

### ISSUE THREAD

**Issue by msowho** [wukko/cobalt#45]
when i trying to downloading video from any tweets, it just says "an error occurred when i tried to get info about your link."
i guess time to check twitter parser lol

video proof:
https://files.catbox.moe/7zln7c.mp4

**Comment by wukko** [comment]
this got fixed [3 minutes ago](https://github.com/wukko/cobalt/commit/94b527afe1233f4dd77309dfa1fba85c60554ad7)

**Comment by msowho** [comment]
bruh

**Comment by wukko** [comment]
im blazingly fast i know i know
