### ISSUE TITLE
[TEMP FIX ON OTHER BRANCH] youtube returns dummy responses (yet again)

### ISSUE THREAD

**Issue by wukko** [wukko/cobalt#450]
### what's known about this issue?
- **applies to all cobalt instances**.
- [temp fix](https://github.com/wukko/cobalt/commit/9bd3ea40e04b9888fa5985914f6851657c67e17c) was made to replace the innertube client with ytmusic one, but may not last long.
- web and ios innertube clients are insanely slow, so we can't use those.
- cobalt isn't the only downloader affected. every downloader that relied on android client is either broken or was forced to switch to a different one.

### what errors apply to this issue?
- "i couldn't connect to the service api".
- "something went wrong when i tried getting info about your link".
- "this youtube video is unavailable"
<img width="434" alt="image" src="https://github.com/wukko/cobalt/assets/71202418/b6088d27-e011-41d7-8509-000ee1f7a5a5">

### what other measures are taken?
- we will revamp the main instance infrastructure soon, less networking issues should happen.

**Comment by lostdusty** [comment]
everyone say thanks wukko

**Comment by saphes** [comment]
thanks wukko

**Comment by LabRatMime** [comment]
thanks wukko

**Comment by qlimq** [comment]
thanks wukko

**Comment by diamvi** [comment]
thanks wukko

**Comment by ryan-huang1** [comment]
thanks wukko

**Comment by SpiritAxolotl** [comment]
thanks wukko

**Comment by 6306** [comment]
thanks wukko

**Comment by wukko** [comment]
please stop saying thanks i didn't do much and it's spamming my email 😭

**Comment by KwiatekMiki** [comment]
thanks wukko
