### ISSUE TITLE
Downloading fails when downloading a TikTok video from any instance except main

### ISSUE THREAD

**Issue by GreeningSiren** [wukko/cobalt#451]
**bug description**
a clear and concise description of what the bug is.
When trying to download a TikTok video using the eu-gb server getting 
"i couldn't find anything about this link. check if it works and try again! some content may be region restricted, so keep that in mind"
**reproduction steps**
steps to reproduce the behavior:
1. go to eu-gb instance
2. Try downloading a TikTok video
3. Get "i couldn't find anything about this link. check if it works and try again! some content may be region restricted, so keep that in mind"

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.

**links**
if applicable, add links that cause the issue. more = better.

**platform**
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]
Android 
Chrome 
Latest version of chrome on android

**additional context**
add any other context about the problem here.

**Comment by GreeningSiren** [comment]
Actually not only eu-gb 
But all except main

**Comment by wukko** [comment]
there's no official instance called "eu-gb", but i can assume that neither of instances you've tried have [configured tiktok correctly](https://github.com/wukko/cobalt/blob/current/docs/run-an-instance.md#tiktok_device_info).

should i rename the issue to "show an appropriate error when tiktok support is not configured on an instance"?

**Comment by lostdusty** [comment]
yes

**Comment by GreeningSiren** [comment]
isn't there an instance on 
https://download.stuff.solutions/
Its listed on the website as eu-gb region

**Comment by wukko** [comment]
it's a community instance, we have no control over it

**Comment by GreeningSiren** [comment]
Can't change community instances so closing the issue
