### ISSUE TITLE
bilibili.com works but m.bilibili.com doesnt

### ISSUE THREAD

**Issue by GreeningSiren** [wukko/cobalt#452]
**bug description**
a clear and concise description of what the bug is.
On main instance using m.bilibili.com url doesn't work while bilibili.com url works

**reproduction steps**
steps to reproduce the behavior:
1. Use main instance
2. Try using m.bilibili.com url 
   Example: https://m.bilibili.com/video/BV1TP411Y7bt
3. Doesn't work 
4. Removing the m. makes it work

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.

**links**
if applicable, add links that cause the issue. more = better.
Doesn't work:
https://m.bilibili.com/video/BV1TP411Y7bt
Works:
https://bilibili.com/video/BV1TP411Y7bt

**platform**
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
fixed in 13d7ca3af441248bc866ed3adf92b29e4c6e33eb
