### ISSUE TITLE
Can't download videos from Pinterest

### ISSUE THREAD

**Issue by KwiatekMiki** [wukko/cobalt#456]
**bug description**
title

**reproduction steps**
steps to reproduce the behavior:
1. go to cobalt.tools
2. click on the input for link
3. download this video: https://pl.pinterest.com/pin/1116681670105166673
4. see error

**screenshots**
![image](https://github.com/wukko/cobalt/assets/79092746/4f82acfe-d08e-45cb-a73f-4da27d4d0d7c)

**links**
https://pl.pinterest.com/pin/1116681670105166673 (it has copyrighted sound btw)
https://pl.pinterest.com/pin/1116681670105166889
https://pl.pinterest.com/pin/1116681670105166912

**platform**
- Windows
- Chrome
- 123

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
fixed in c86e209e55fe21443fd83c6c27c5b7ff073e2033
