### ISSUE TITLE
rutube returns 0 byte videos

### ISSUE THREAD

**Issue by KwiatekMiki** [wukko/cobalt#457]
**bug description**'
title

**reproduction steps**
steps to reproduce the behavior:
1. go to '...'
2. click on '....'
3. download this video: **[link here]**
4. see error

**screenshots**
![image](https://github.com/wukko/cobalt/assets/79092746/2d1b21e5-53dc-4be4-9d62-36e0a605dd2b)

**links**
https://rutube.ru/video/5087d1e93842128039b925a73e420a26/
https://rutube.ru/video/8c47c42e49313890ea8c19f430f8033e/

**platform**
- Windows
- Chrome
- 123

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
this was a temporary issue with us testing new stuff in prod, should be fine now

**Comment by KwiatekMiki** [comment]
working now thx
