### ISSUE TITLE
Add support for /channels/uploader/id vimeo links 

### ISSUE THREAD

**Issue by KwiatekMiki** [wukko/cobalt#458]
https://vimeo.com/channels/staffpicks/936245676

**Comment by KwiatekMiki** [comment]
my issues keep getting lazier and lazier

**Comment by KwiatekMiki** [comment]
soo how was it downloadable before?

**Comment by wukko** [comment]
you used a different link, such as: https://vimeo.com/936245676

**Comment by KwiatekMiki** [comment]
oh ok i never used vimeo
