### ISSUE TITLE
Twitter API url

### ISSUE THREAD

**Issue by paintingofblue** [wukko/cobalt#46]
https://cdn.syndication.twimg.com/tweet?id= Afaik this endpoint isn't rate limited & doesn't require a bearer token, may be better to use for this site

Example response from that url: https://upload.systems/p/1z9jHMKO8u7V

**Comment by wukko** [comment]
oh damn this is nice thank you

**Comment by paintingofblue** [comment]
np, figured it'd be a lot better to use, needs a tweet id but i included that parameter in the url
