### ISSUE TITLE
Tiktok workflow is broken

### ISSUE THREAD

**Issue by Port2all** [wukko/cobalt#47]
Tested it locally on latest version, and also manually tested script part for tiktok.
Looks like it gives an error on step when you're trying to get html body of post page, before searching of file src.

Also I've found something strange in response 
```
rejectUnauthorized: true,
session: undefined,
```
Maybe now we need to login before trying to find source link. 
Any ideas?

**Comment by wukko** [comment]
damn why can't bytedance just let me live

**Comment by wukko** [comment]
ill see what's up in a bit and reply with what i think is wrong

**Comment by wukko** [comment]
they simply killed the feed api endpoint, wow

**Comment by wukko** [comment]
cant find another one that'd work :(

**Comment by Port2all** [comment]
Maybe we can use some headless browser for getting the page and parse for video source?

**Comment by Port2all** [comment]
I've played a little with puppeteer
<img width="713" alt="image" src="https://user-images.githubusercontent.com/7143962/197221778-e849f6a5-4f7b-4b59-a0a3-2f656c2bbf3d.png">
<img width="2561" alt="image" src="https://user-images.githubusercontent.com/7143962/197221827-585f19fd-40a1-4a18-ae21-c432ffb5d11f.png">
Looks like we still can get the link :)

What do you think, it can work as workaround?

**Comment by wukko** [comment]
this is a watermarked video, and cobalt already gets it when the preference for non watermarked videos is not set

currently nothing works at all because there's an additional check before that which includes seeing whether there are photo slides in the post or not

**Comment by Port2all** [comment]
@wukko not working now :(

**Comment by wukko** [comment]
it works just fine on [co.wukko.me](https://co.wukko.me/) and locally for me

![image](https://user-images.githubusercontent.com/71202418/199487373-551cb704-ea5e-4c00-ac06-bfca556efab5.png)

**Comment by Port2all** [comment]
My bad. After reinstalling of modules it works.
Shit, they really changing endpoints for video twice a month?)
