### ISSUE TITLE
connectivity issues on main instance

### ISSUE THREAD

**Issue by ithinkiknowhowtocoed** [wukko/cobalt#479]
steps to reproduce the behavior:
1. go to youtube.com
3. download this video: **[https://www.youtube.com/watch?v=k55FYtqtXXU]**
4. see error

**screenshots**
![cobalt down](https://github.com/wukko/cobalt/assets/168694400/92413037-d4a7-46b3-b8d9-0c30f78f3e27)

**links**
all links i used

**platform**
- OS [mac os 14]
- browser [firefox]

api issue

**Comment by wukko** [comment]
we're aware of spotty connectivity issues and are waiting for royalehosting to do at least *something*. it's out of our control.

**Comment by wukko** [comment]
moving this issue to #480
