### ISSUE TITLE
YouTube videos appear to return zero bytes for a prolonged period of time

### ISSUE THREAD

**Issue by prettybadatcoding** [wukko/cobalt#482]
**bug description**
a clear and concise description of what the bug is.
cobalt appears to be returning an empty file (just the title of the video and the data)

**reproduction steps**
steps to reproduce the behavior:
1. go to 'cobalt.tools'
3. download this video: **https://www.youtube.com/watch?v=9U9WmFIGtUA**
4. file downloads instantly; 0 bytes

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.
![image](https://github.com/wukko/cobalt/assets/97399364/1ceb3427-2bf4-4017-9f4a-2a4e7b87bac4)

**links**
if applicable, add links that cause the issue. more = better.
https://www.youtube.com/watch?v=9U9WmFIGtUA 
this video on Hurricane Ian

**platform**
- OS - Windows 11 Home
- browser - Google Chrome
- version - 124.0.6367.93

**additional context**
add any other context about the problem here.

**Comment by wukko** [comment]
hey! can you try again? i fixed the issue with one of processing servers

**Comment by prettybadatcoding** [comment]
ok it works now! thanks

**Comment by dhawansolanki** [comment]
> hey! can you try again? i fixed the issue with one of processing servers

What exactly does the processing server means?

**Comment by wukko** [comment]
> What exactly does the processing server means?

i was talking about the cobalt api there! it's the server that handles all requests.
