### ISSUE TITLE
1080p 60 FPS video support for TikTok downloads

### ISSUE THREAD

**Issue by KK-Designs** [wukko/cobalt#488]
**describe the feature you'd like to see**
The current HEVC downloader in cobalt.tools downloads videos at 576x1024 only at 30fps, which is not 1080p like said in the settings toggle.

**additional context**
From cobalt:
![Screenshot_20240505_173211_MediaInfo.png](https://github.com/wukko/cobalt/assets/71038229/60bb2399-c987-457a-9ed4-0e5f6bd33511)

From MusicalDown:
![Screenshot_20240505_173239_MediaInfo.png](https://github.com/wukko/cobalt/assets/71038229/21dd6a1e-64fb-4341-ac06-ae4836efee74)

**Comment by wukko** [comment]
can you send a link that's affected? have you toggled "prefer h265" in settings?

**Comment by KK-Designs** [comment]
> can you send a link that's affected? have you toggled "prefer h265" in settings?

Same effect across every tiktok of that quality

[the link I used in the video, converted to the permalink](https://www.tiktok.com/@miivai/video/7361289046783511850?_t=8m8Djtc0RQd&_r=1)

Screenrecording:
https://github.com/wukko/cobalt/assets/71038229/150dfeb4-2f08-4532-af3b-3a4647ae3019

**Comment by wukko** [comment]
addressed in bdcb57f

**Comment by KK-Designs** [comment]
The bitrate from musicaldown.com on HD videos seems to be a lot higher than what cobalt returns, 1.5mbps to 8mbps, could that be an easy fix? Or is cobalt returning the true bitrate for the video stream?
