### ISSUE TITLE
YouTube mp4 videos are impossible to play properly on less advanced players

### ISSUE THREAD

**Issue by SirAxolot** [wukko/cobalt#5]
i downloaded a youtube video and tried to trim it using the windows video trimmer, it wouldnt let me trim it. also this happened
![image](https://user-images.githubusercontent.com/89815386/180669071-209d30e1-f37e-4aa5-9423-28d7377da8b3.png)
(i dowloaded it as a max-quality mp4)
if i tried to import it into any other video editor it shows an error

when i try to view the file's properties it shows a null length, and 0kbps audio??? im not exactly an ffmpeg master so i dont exactly know what causes this
![image](https://user-images.githubusercontent.com/89815386/180669145-e34b9729-e66d-4ae9-a1f9-154796fceab8.png)

also the file opens normally when viewing it
![image](https://user-images.githubusercontent.com/89815386/180669203-fa13f949-70dd-4486-b131-8ec23186c55c.png)

**Comment by msowho** [comment]
probably this is ffmpeg bug.

**Comment by msowho** [comment]
btw you can send your corrupted vfideo, i will check it and maybe fix this problem.

**Comment by wukko** [comment]
you can download any youtube video in resolution different from 720p and you'll get this broken video

**Comment by wukko** [comment]
i tried to fix this without harming the performance not that long ago and failed 💯

**Comment by msowho** [comment]
ffprobe shows nothing wrong
https://ibb.co/vq2pj6Y

**Comment by msowho** [comment]
lemme try to download video with bigger duration

**Comment by wukko** [comment]
yea cause videos themselves are not broken, it's just that some video players hate the format youtube uses

**Comment by msowho** [comment]
oh

**Comment by wukko** [comment]
even browsers are fine with videos cobalt makes

**Comment by msowho** [comment]
i guess we have to do transcoding video/audio bruh.

**Comment by msowho** [comment]
because how i understand youtube uses non-standard audio format in webm container for serve audio from videos

**Comment by kotobdev** [comment]
Probably related to this- Windows Movies whines about any youtube video I try to download in 4K. Unfortunately, Blender does as well, which is a bit odd. However, the audio still works in these videos. Interestingly, while downloading at 720p fixes the video codec thing, it doesn't fix the null length bug.
![image](https://user-images.githubusercontent.com/59124164/182997528-71f1c69b-791f-4826-a626-8c38d58ca10b.png)

**Comment by wukko** [comment]
vlc, mpv, and any chromium browser can play back any mp4 video from cobalt without any issues 
![screenshot of mpv playing back mp4 video from cobalt with normal video length shown](https://user-images.githubusercontent.com/71202418/183251247-5d2b094f-57b4-4356-bc8e-b988e00bb928.png)
![screenshot of chrome playing back mp4 video from cobalt with normal video length shown](https://user-images.githubusercontent.com/71202418/183251277-6ff071f8-3adf-4f10-8fe5-a5a412142d53.png)

**Comment by Zulfen** [comment]
the length issue only occurs on windows movies - i think it's just due to codec support. all videos work fine in video editors and on browsers etc.

**Comment by wukko** [comment]
@Zulfen that's exactly what i mean by "less advanced players"
