### ISSUE TITLE
Public Twitter accounts that were flagged as adult content or age-restricted are no longer possible to download images, videos or mixed media from

### ISSUE THREAD

**Issue by 64ut15t4** [wukko/cobalt#51]
Previously, Cobalt allowed you to download images, videos and mixed media from any public account. Then, downloading mixed media bugged out—only allowing the first image or video in a series of four. Then, now it just completely disallows download from age-restricted accounts even if they're public.

The error message is:

```
uh-oh...

an error occurred when i tried to get info about your link. are you sure it works? check if it does, and try again.
```

Here's an example link, from a person uploading "safe" samples of his paid content: https://twitter.com/leathersambam88/status/1589098906616745986 - Try loading his profile in incognito/private mode and it would show the age-restricted message. Cobalt used to be able to download these just fine.

**Comment by wukko** [comment]
1. i didn't need to know about your leather kink
2. i had to choose between mixed media tweets support and explicit content, ive chosen the former one.

i simply need an app token that'd tell api to spit out both mixed media stuff and nsfw content, but i couldn't find one anywhere in the open. at least back when i was working on that update. 

i've also mentioned this in the changelog upon change

**Comment by wukko** [comment]
added support for this in 4.3.2, have fun
