### ISSUE TITLE
Add support for vxtwitter and fxtwitter URLs

### ISSUE THREAD

**Issue by supern64** [wukko/cobalt#52]
Sometimes my friends send me a vxtwitter or fxtwitter URL, like this one
https://vxtwitter.com/RayaanTheAlien/status/1455029356032499714
It's basically only there to make the video embed better on Discord, and I'd assume cobalt could be able to handle these like it handles normal Twitter URLs.

P.S. I've been using cobalt for a while, and I absolutely love it! Thank you for your work!

**Comment by Whanos** [comment]
For the time being you can just remove the vx from vxtwitter.com.

**Comment by supern64** [comment]
> For the time being you can just remove the vx from vxtwitter.com.

i'm aware, i just wanted it to be one click lol

**Comment by wukko** [comment]
don't know if adding support for 3rd party urls would be safe or practical

**Comment by jojobii-arks** [comment]
How about having this switch statement's case clause for `"twitter"` also be used for those third-party URLs, with like a message saying that it's parsing the link as if the host name is `"twitter"`?

https://github.com/wukko/cobalt/blob/7f1ba6b36ba8d6098e9c6d8a4f2338acbf57abdf/src/modules/processing/match.js#L26-L33

I'll come back to this thread with a fork with my idea lol

**Comment by wukko** [comment]
won't do, these services come and go and supporting them all would be an unnecessary hassle.

just remove two letters from the pasted link!

**Comment by jojobii-arks** [comment]
LOL fair enough 👍
