### ISSUE TITLE
I'm not able to download anything

### ISSUE THREAD

**Issue by tygerxqt** [wukko/cobalt#53]
Hello, 

I tried going to https://co.wukko.me/ and I pasted the link `https://www.youtube.com/watch?v=OvhVLmD0DfQ` with auto mode on and I got the error saying that I have sent too many requests. However, the issue is that I haven't even used the site yet. I have visited the site before to check it out and see how it worked but never used it to download anything. And no, I didn't spam the button, I pressed it once.

Hope this issue is resolved soon, this site looks promising!

**Comment by tygerxqt** [comment]
I did some testing and all chromium browsers work however firefox gives the error, this might be a browser issue on my end instead of the site.

**Comment by wukko** [comment]
do you happen to be using a public, free vpn?

**Comment by wukko** [comment]
the link is just fine, it's just that the rate limit has been exceeded for your ip address 

![screenshot](https://user-images.githubusercontent.com/71202418/200976502-d777bedd-4806-459e-8443-05a2fcf2e67b.png)

try:
- switching to another server if you're using a vpn
- rebooting your router
- using a vpn, if you're not actually using one
- simply waiting for an hour for limit to renew

im planning to significantly rise up the rate limit threshold in coming days, cause main instance of cobalt is now hosted on a way more powerful server, which can process more requests at once.

**Comment by tygerxqt** [comment]
Those steps helped me out, I completely forgot I was running a VPN. Sorry for the confusion!
