### ISSUE TITLE
CORS restricts API access

### ISSUE THREAD

**Issue by kotobdev** [wukko/cobalt#57]
I'm not sure if this is intentional or not, but trying to access an API endpoint at co.wukko.me via JavaScript (in this case, within a Firefox extension) will throw a CORS error, probably due to the header `access-control-allow-origin: https://co.wukko.me/`. I'm not sure, but I'd assume this is not intended behavior for an open API. 
![Screen Shot 2022-11-17 at 9 47 01 AM](https://user-images.githubusercontent.com/59124164/202519976-3b266e22-8872-4594-a251-f600d2d97fea.png)

**Comment by sparkyfen** [comment]
Isn't the syntax `https://co.wukko.me/api/json?url=https://youtube.com/shorts/c7I-q7r4bIo`

**Comment by kotobdev** [comment]
Ah, yeah, it is. Regardless, it'll still give a CORS error if the request is made anywhere but the web console at `co.wukko.me`.
![image](https://user-images.githubusercontent.com/59124164/202886869-8e9ec57d-59d3-46a8-8c9c-15d584f8a13d.png)

**Comment by wukko** [comment]
> Isn't the syntax https://co.wukko.me/api/json?url=https://youtube.com/shorts/c7I-q7r4bIo

no, [it's POST request](https://github.com/wukko/cobalt/blob/current/docs/API.md#post-apijson) to https://co.wukko.me/api/json. no query, just the post body

**Comment by wukko** [comment]
CORS limits DDOS surface + prevents people from using cobalt's api on sites that may be filled with ads
