### ISSUE TITLE
Spotify Links not supported

### ISSUE THREAD

**Issue by axiinyaa** [wukko/cobalt#58]
**I wanna download my spotify songs! (it would be awesome!!!)**

**Comment by Axiinyaa** [comment]
Also great job, a universal downloader is so useful! Thank you!

**Comment by wukko** [comment]
adding spotify support would inevitably lead to a dmca claim that'd take the repo (and main instance) down. download songs from youtube music instead!

**Comment by Malix-off** [comment]
@wukko it would be better to close this as unplanned 🙂

**Comment by Malix-off** [comment]
## Proposed Workaround

An option to download from another source (potentially YouTube Music?) when a Spotify link has been submitted (fetch the song name from the link, which would probably not be against their ToS)
