### ISSUE TITLE
Memory leak issue caused by incorrect node-cache configuration

### ISSUE THREAD

**Issue by wukko** [wukko/cobalt#63]
no idea if this is caused by cobalt itself or my nginx configuration, but after a few days way more ram is used by the server that cobalt is hosted on. i'll have a look into this issue in a few days (if ram usage ramps up again). if you host your own instance, you can help by checking if this issue applies to you too.

![image](https://user-images.githubusercontent.com/71202418/208229039-58e513b3-f006-497c-825f-8a611a34c386.png)

**Comment by lurkook** [comment]
i recommend to debug node-cache library if it really cleans expired stream metadata.

**Comment by wukko** [comment]
@lurkook you were right, it is the node-cache library, i've fixed the issue and will publish the commit later today

https://wetdry.world/@w/109682355531091033
