### ISSUE TITLE
Audios not downloading fully

### ISSUE THREAD

**Issue by SenMods** [wukko/cobalt#66]
I tried with bloody mary sped up but it stopped at 260 kilobytyes and it never continued

**Comment by wukko** [comment]
what are the audios you tried to download?

**Comment by SenMods** [comment]
From youtube and i was trying in mp3

**Comment by wukko** [comment]
what videos **exactly**

**Comment by SenMods** [comment]
lemme find it

**Comment by SenMods** [comment]
this one https://www.youtube.com/watch?v=EAyzHnbN05Y

**Comment by jaredmassey** [comment]
I'm seeing the same thing, a couple random example videos: https://www.youtube.com/watch?v=BVmYxQT7vyk goes silent for the last 22sec, https://www.youtube.com/watch?v=h5PiROGaPXg goes silent for the last 60sec. 
I can't find any common amount of time or proportion of time that is lost, but on a given video, if I try to re-download it, it seems to be the same amount every time.
Firefox 109.0b4 (64-bit) on Win 10, if that makes any kinda difference.

**Comment by jaredmassey** [comment]
Tried in Brave this morning and also get blocks of silence at the end, but the silence starts sooner / there's more of it than when I tested them in FF last night.

**Comment by wukko** [comment]
browser doesn't matter, seems like #62 is related to this
