### ISSUE TITLE
.ogg audio files unexpectedly include video stream

### ISSUE THREAD

**Issue by lurkook** [wukko/cobalt#67]
I don't know how this was fixed before my bug report, but yeah...

![image](https://user-images.githubusercontent.com/117036757/208716727-630d117d-7620-4a29-8ec9-752e56a7d3e5.png)

This looks like FFmpeg misconfiguration and it does Thoera codec video with default settings.

**Comment by lurkook** [comment]
After FFprobe check, this is probably only Twitter problem.

![image](https://user-images.githubusercontent.com/117036757/208717336-230c6142-f871-4148-88a5-0cba4690ae5e.png)

**Comment by wukko** [comment]
oops
