### ISSUE TITLE
Replace AV1 codec with H264 for mp4 videos downloaded from YouTube

### ISSUE THREAD

**Issue by underscoresnazzy** [wukko/cobalt#69]
no idea what's the problem, whether it's cobalt or something on my end, but i've attached a video describing it
thank u in advance xx

https://user-images.githubusercontent.com/122113179/211060855-3c31fbd2-abc0-4921-9a17-5771122ce16b.mp4

**Comment by wukko** [comment]
this happens because older software (such as vegas) *really* doesn't like av1 format which youtube tends to use for mp4 streams.

however, i'm planning to find a way to get exclusively h264 mp4 videos from youtube in the future

**Comment by Sqaaakoi** [comment]
would you mind also adding an option to allow switching between h264 and av1 in the settings if this becomes a feature?

**Comment by wukko** [comment]
> would you mind also adding an option to allow switching between h264 and av1 in the settings if this becomes a feature?

yes, of course!
