### ISSUE TITLE
TikTok links with dots on the username dont work

### ISSUE THREAD

**Issue by Sarayalth** [wukko/cobalt#71]
TikTok links can include the username in them, and usernames can include dots, seems like cobalt breaks trying to recognize them as tiktok links and throws an "it seems like this service is not supported yet or your link is invalid."
example link: https://www.tiktok.com/@random.video.on.tiktok/video/7090355705605016859

also, as a band-aid fix, seems like replacing the username with something else without the dots makes it work on cobalt, as tiktok redirects to the good one.
`https://www.tiktok.com/@a/video/7090355705605016859`

**Comment by wukko** [comment]
cobalt actually uses just the post id, i'll look into it and see what causes it to bug out, thank you :)
