### ISSUE TITLE
Problem with processing mp4 audio

### ISSUE THREAD

**Issue by milkvoli** [wukko/cobalt#75]
On mobile, I have been constantly facing an issue when I try to download any youtube video that’s longer than 1 minute to an mp4. I find that usually after the first half, the video is suddenly missing its audio.

I have yet to check if I face the same issue on pc, so keep that in mind. If needed, I could go check when I have time.

**Comment by wukko** [comment]
#62

**Comment by wukko** [comment]
what OS does your phone run? and what browser is this issue present in?

**Comment by milkvoli** [comment]
> > what OS does your phone run? and what browser is this issue present in?
> 
> Latest iOS update (16.2), and I only use safari, I didn’t think about checking a different browser, I could try chrome perhaps. Will update!

I checked chrome, met with the same issue. I doubt it has anything to do with the browser. I also checked the issue you linked, I have to say I doubt it has anything to do with download speed because the wifi I am connected to has zero performance issues.
