### ISSUE TITLE
Add support for Reddit GIFs 

### ISSUE THREAD

**Issue by thepwrtank18** [wukko/cobalt#80]
![image](https://user-images.githubusercontent.com/57580668/217378751-01a175bd-1dd1-43e1-bd0f-272132f53d1d.png)
Attempted to download `https://www.reddit.com/r/whenthe/comments/10vxtjj/imagine_using_this_against_like_a_fucking_cartel/`

**Comment by wukko** [comment]
added in 5.0 :D
