### ISSUE TITLE
Add estimated file size to stream API responses

### ISSUE THREAD

**Issue by easrng** [wukko/cobalt#83]
For streamDefault just pass through the Content-Length header, for the rest parsing the ffmpeg output might be required. I can send a PR, do you have example URLs/settings for all the different types?

**Comment by wukko** [comment]
> what code formatter do u use btw
just my head really, dont know of any that wouldn't piss me off

**Comment by wukko** [comment]
there are many variations of requests in tests, they might be useful for you
