### ISSUE TITLE
YouTube not working on self-hosted instance

### ISSUE THREAD

**Issue by hyperdefined** [wukko/cobalt#86]
I have my own instance hosted here: https://co.hyper.lol

YouTube videos/audios don't seem to work, and always result in a HTTP 400 error. Not sure what I can look into for this.

I am running commit 9b17300492d589fa0a3efbd589e8edf4b0f848dd.

![image](https://cdn.upload.systems/uploads/hINMHz1G.png)
![image](https://cdn.upload.systems/uploads/H48GRZ1B.png)

Any video I try results in this. Could it be something with Cloudflare?

**Comment by wukko** [comment]
have you run the setup script? streamable content won't work without stream salt

**Comment by hyperdefined** [comment]
Yes, I have ran the setup and confirmed there is a stream salt in the `.env` file.

**Comment by wukko** [comment]
huh. that's weird.

try adding `console.log(e);` above 127th line [in this file](https://github.com/wukko/cobalt/blob/9b17300492d589fa0a3efbd589e8edf4b0f848dd/src/modules/processing/match.js#L127), and see if there's anything in console.

i know this isn't an ideal way to debug errors, and have now added “proper debugging” to my to-do list for next update.

are you sure all modules are intact, including `better-ytdl-core`? have you modified any other files? is node.js version on your machine newer than minimum one (17.5)?

**Comment by hyperdefined** [comment]
This is very strange, it now randomly works. I have no clue what changed.

I added that line and it didn't print anything, so god knows what went wrong earlier.

To answer you question, I have not modified any files. I made sure to have all modules installed (including `better-ytdl-core`). I am using node.js v18.14.1.

**Comment by wukko** [comment]
probably temporary network issue with youtube or something, lmk if you experience any other issues :D
