### ISSUE TITLE
Audio of a certain youtube video cuts out in the middle when downloading in video mode

### ISSUE THREAD

**Issue by breakgimme** [wukko/cobalt#88]
When downloading [ぼっちロック](https://www.youtube.com/watch?v=V6JJ69Scj24) in video mode, its audio cuts out at around the 1-minute mark. It isn't consistent, sometimes it happens earlier, sometimes later (differs by only a couple of seconds) and it doesn't happen when downloading it in audio mode. This video seems to have some issues on youtube itself, since (at least for me) also around the 1-minute mark the video briefly stops and buffers before resuming.

**Comment by wukko** [comment]
same issue as #62

**Comment by breakgimme** [comment]
oh, sorry for making a duplicate
should i close it?

**Comment by wukko** [comment]
nah, it's okay. 
i left this issue open because you provided a new example, and that'll be handy! thank you :)
