### ISSUE TITLE
Sometimes cobalt isn't able to get AV1/VP9 videos

### ISSUE THREAD

**Issue by thepwrtank18** [wukko/cobalt#89]
Video in question: https://www.youtube.com/watch?v=MDsJJRNXjYI
suggested approach is to use the next best thing (vp9, h264)

**Comment by wukko** [comment]
cobalt handles this error since 5.1.1, but i will soon push an update with which it'll get even more av1/vp9 videos

**Comment by wukko** [comment]
unable to solve this issue at current date, youtube api just won't give out av1 videos for certain videos no matter the client :(
