### ISSUE TITLE
/api/stream returns Unauthorized

### ISSUE THREAD

**Issue by thepwrtank18** [wukko/cobalt#91]
When making a POST request with the following data:
```json
{"url": "https://www.youtube.com/watch?v=[url]"}
```

it returns 200 OK with the following data:
```json
{
    "status": "stream",
    "url": "https://co.wukko.me/api/stream?t=[...]&e=[...]&h=[...]"
}
```

Opening that URL returns this:
```json
{"status":"error","text":"Unauthorized"}
```

**Comment by wukko** [comment]
does it happen with all videos you've tried, or only some? is only youtube affected?

**Comment by wukko** [comment]
as you haven't replied in 2 months, i suppose the issue has been solved.
