### ISSUE TITLE
Why not use yt-dlp as a backend ?

### ISSUE THREAD

**Issue by SuwakoMmh** [wukko/cobalt#95]
First of all, congratulations for the flabbergasting project. The front-end is simple and pleasant !

I am just wondering why you don't use **yt-dlp** as a back-end to fetch videos and audio.
It is very well maintained, supports a very long (this is an understatement) list of websites, **including all the ones cobalt currently supports**.
It supports extracting the different audio, video, subtitles and other tracks/metadata.

Since it's well maintained and used by many projects, any issue related to an API update from one of the websites will be fixed quickly.

Why bother doing it from scratch ?

**Comment by wukko** [comment]
here's why i didn't use yt-dlp:
1. 0 control over unreadable code
2. no strong link between python child process and node.js base
3. unnecessary possibility for security issues
4. unpleasant api
5. unknown stability and speed
6. questionable maintenance

making my own modules, on the other hand, eliminates all these issues.
- i have FULL control over READABLE code
- all modules are strongly tied to base code
- obviously parsing in js is faster than running a python child process
- everything works in perfect harmony

this way i am also the one responsible for all issues, and i do not want to redirect the blame on someone else in case anything goes wrong.

**Comment by melyux** [comment]
You also lose support for websites that yt-dlp supports though.
