### ISSUE TITLE
Desktop TikTok links with periods in username don't work

### ISSUE THREAD

**Issue by busybox11** [wukko/cobalt#96]
Example of unsupported link: https://www.tiktok.com/@.thicccat69/video/7209322948207873285
Can be found by accessing TikTok from the desktop website
If I have time to take a look at it soon and try to do a PR, I'll keep you updated.

**Comment by wukko** [comment]
hey! the issue is actually with a dot in the user name, if you replace it (or entire username) with anything else, it'll work. cobalt only uses the post id.

i'm aware of this issue but forgot to put it on to-do list, thank you.

**Comment by wukko** [comment]
this bug is just an oversight by me, iirc cobalt gets the service name by splitting the url by ".", should definitely change that (and update the entire related function as i did with all the rest)
